In [6]:
from pathlib import Path
import pandas as pd

# 兼容运行目录为项目根目录或 notebooks
data_dir = Path("data")
if not data_dir.exists():
    data_dir = Path("../data")

chem = pd.read_csv(data_dir / "1.csv")
sensory = pd.read_csv(data_dir / "4.csv")

print("化学数据：", chem.shape)
print("感官数据：", sensory.shape)

display(chem.head())
display(sensory.head())

merged = chem.merge(
    sensory,
    on="beer",
    validate="one_to_one",
    suffixes=("_chem", "_sensory")
)
print("匹配啤酒数量：", len(merged))

化学数据： (250, 234)
感官数据： (250, 53)

,beer,beer_id,tasting_category_fine,acetaldehyde,CS2,DES,DMS,ethyl_2.methyl_butyrate,ethyl_acetate,ethyl_decanoate,...,X13.epi.manool.oxide,isopropyl.hexadecanoate,manool,ethyl.octadecanoate,ethyl.pentanoate,X2.ethyl.3.methylpyrazine,esters_sum,aroma_hops_sum,acids_sum,sulfur_sum
0,10,5410228202929,Low/No alcohol,-0.641741,-2.146292,-1.905267,0.046211,-3.19552,-0.599350,-1.975309,...,4.360243,-1.817819,5.721204,4.438951,0.014728,0.054353,-0.532634,3.696586,0.244085,0.166286
1,86,5410783031019,Low/No alcohol,-0.174824,-2.146292,-0.257098,0.347241,-3.19552,-0.507254,-1.755970,...,4.512589,4.323292,5.810501,4.247826,0.023167,0.001400,-0.465401,1.219563,-0.152156,0.098931
2,2,5410228142003,Low/No alcohol,0.511067,-2.146292,-1.905267,0.898604,-3.19552,-0.134514,-1.893639,...,4.394267,-1.817819,5.585529,3.598293,0.017571,0.000699,-0.409346,1.148974,-0.161504,-0.022943
3,83,54055520,Low/No alcohol,0.249793,-2.146292,-1.905267,0.782126,-3.19552,-0.233874,-2.086981,...,4.174304,4.088807,5.204583,4.498781,0.016959,0.001101,-0.420080,1.416847,-0.056092,0.068372
4,40,5410228141181,Low/No alcohol,-1.902829,-0.756987,-1.347270,0.553356,-3.19552,0.207751,-1.713095,...,4.742899,4.651536,6.515499,4.789220,0.117921,0.000492,-0.144457,0.672328,-1.204001,0.639462

,beer,beer_id,tasting_category_fine,A_malt_all,A_malt_grain,A_malt_bread,A_malt_cara,A_malt_burn,A_hops_all,A_hops_citrus,...,coriander,clove,lactic,acetic,barnyard,alcohol,aftertaste,body,co2,overall
0,10,5.410230e+12,Low/No alcohol,-0.481208,-0.179070,-0.464636,-0.554391,-0.384540,-0.022010,0.843613,...,0.783631,2.828355,-0.162975,-0.282149,-0.357290,-1.807336,-1.682733,-0.630386,-1.043431,-0.467852
1,86,5.410780e+12,Low/No alcohol,1.678276,1.759243,0.356967,0.649475,0.687970,-0.735573,-0.493721,...,-0.213168,-0.225153,-0.314574,-0.282149,-0.357290,-1.974904,-1.456136,-1.380574,-0.408753,-0.994806
2,2,5.410230e+12,Low/No alcohol,-0.135865,0.215999,-0.083786,-0.554391,-0.384540,-1.192019,-0.493721,...,-0.213168,-0.225153,-0.314574,-0.282149,-0.357290,-1.990725,-1.647121,-1.169839,-1.353028,-1.528544
3,83,5.405552e+07,Low/No alcohol,0.538252,1.059832,0.486692,-0.554391,-0.384540,-0.668249,0.145775,...,-0.213168,-0.225153,-0.314574,-0.282149,-0.357290,-2.150729,-1.801023,-0.997524,-1.045610,-0.934138
4,40,5.410230e+12,Low/No alcohol,-0.437823,-0.507368,0.076957,-0.503614,-0.277529,-0.498430,-0.492765,...,-0.236605,-0.248292,-0.307380,-0.269671,-0.331149,-1.681082,-2.100345,-1.862278,-1.739428,-1.735965

匹配啤酒数量： 250

In [7]:
print("化学表编号缺失数：", chem["beer"].isna().sum())
print("感官表编号缺失数：", sensory["beer"].isna().sum())
print("两表编号集合一致：",
      set(chem["beer"]) == set(sensory["beer"]))

print("\n化学表缺失单元格总数：", chem.isna().sum().sum())
print("感官表缺失单元格总数：", sensory.isna().sum().sum())

missing = chem.isna().sum()
print("\n存在缺失值的化学表字段：")
print(missing[missing > 0].sort_values(ascending=False).to_string())

print("\n化学表非数值字段：")
print(chem.select_dtypes(exclude="number").columns.tolist())

print("\n感官表全部字段：")
print(sensory.columns.tolist())

化学表编号缺失数： 0
感官表编号缺失数： 0
两表编号集合一致： True

化学表缺失单元格总数： 73
感官表缺失单元格总数： 0

存在缺失值的化学表字段：
amyl.acetate          27
aroma_hops_sum        13
methylpyrazine        12
X2.3.butanedione       9
X3.methylbutanal       7
ethyl.nicotinate       2
ethyl.isobutyrate      1
furfural               1
phenylacetaldehyde     1

化学表非数值字段：
['tasting_category_fine']

感官表全部字段：
['beer', 'beer_id', 'tasting_category_fine', 'A_malt_all', 'A_malt_grain', 'A_malt_bread', 'A_malt_cara', 'A_malt_burn', 'A_hops_all', 'A_hops_citrus', 'A_hops_tropical', 'A_hops_noble', 'A_hops_woody', 'A_esters_all', 'A_esters_ethac', 'A_esters_isoaa', 'A_esters_flower', 'A_esters_fruity', 'F_malt_all', 'F_malt_grain', 'F_malt_bread', 'F_malt_cara', 'F_malt_burn', 'F_hops_all', 'F_hops_citrus', 'F_hops_tropical', 'F_hops_noble', 'F_hops_woody', 'F_esters_all', 'F_esters_ethac', 'F_esters_isoaa', 'F_esters_flower', 'F_esters_fruity', 'acidity', 'bitternes', 'sweetness', 'X4vg', 'diacetyl', 'dms', 'metallic', 'stale_hops', 't2n', 'orange', 'coriander', 'clove', 'lactic', 'acetic', 'barnyard', 'alcohol', 'aftertaste', 'body', 'co2', 'overall']

In [8]:
# 用编号作为行标签，并按编号排序
chem_aligned = chem.set_index("beer").sort_index()
sensory_aligned = sensory.set_index("beer").sort_index()

# 检查两表每一行是否对应同一款啤酒
assert chem_aligned.index.equals(sensory_aligned.index)

# 排除编号和风格，保留候选化学输入
X = chem_aligned.drop(columns=["beer_id", "tasting_category_fine"])

# 排除编号和风格，保留全部评分，具体建模目标后续再核对
Y = sensory_aligned.drop(columns=["beer_id", "tasting_category_fine"])

print("候选输入 X：", X.shape)
print("全部评分 Y：", Y.shape)

# 查看每项评分的分布
score_summary = Y.describe().T[["min", "max", "mean", "std"]]
print("\n前8项评分的统计：")
print(score_summary.head(8).round(3).to_string())

候选输入 X： (250, 231)
全部评分 Y： (250, 50)

前8项评分的统计：
                   min    max   mean    std
A_malt_all      -1.552  2.876  0.037  0.717
A_malt_grain    -0.971  1.759  0.018  0.457
A_malt_bread    -0.690  2.462  0.047  0.523
A_malt_cara     -0.599  2.193  0.025  0.628
A_malt_burn     -0.447  4.104  0.019  0.681
A_hops_all      -1.362  2.488  0.001  0.660
A_hops_citrus   -0.580  1.818 -0.012  0.487
A_hops_tropical -0.524  3.064  0.008  0.611

In [9]:
rating_book = pd.ExcelFile(data_dir / "3.xlsx")
print(rating_book.sheet_names)

['beer_1', 'beer_2', 'beer_3', 'beer_4', 'beer_5', 'beer_6', 'beer_7', 'beer_8', 'beer_9', 'beer_10', 'beer_11', 'beer_12', 'summary']

In [10]:
sample_sheet = pd.read_excel(
    rating_book,
    sheet_name="beer_1",
    header=None
)

print("表格大小：", sample_sheet.shape)
print(sample_sheet.head(20).to_string(index=False, header=False))

表格大小： (101, 33)
NaN  Date NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN Name: NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  Beer#: 1.0 NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN Aroma NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN Flavour NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN  Malt NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    Malt NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0
NaN   NaN 0.0 NaN                      1 NaN 2.0 NaN 3.0 NaN 4.0 NaN 5.0 NaN 6.0 NaN NaN     NaN 0.0 NaN                      1 NaN 2.0 NaN 3.0 NaN 4.0 NaN 5.0 NaN 6.0 NaN NaN
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN Cereals, flour, grains NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0     NaN NaN NaN Cereals, flour, grains NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN            Bread crust NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0     NaN NaN NaN            Bread crust NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN                Caramel NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0     NaN NaN NaN                Caramel NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN    Smoked, burnt toast NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0     NaN NaN NaN    Smoked, burnt toast NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN  Hops NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN    Hops NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
NaN   NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0     NaN NaN NaN                    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.0

In [11]:
from openpyxl import load_workbook

book = load_workbook(data_dir / "3.xlsx", data_only=False)
sheet = book["beer_1"]

formulas = [
    (cell.coordinate, cell.value)
    for row in sheet.iter_rows()
    for cell in row
    if cell.data_type == "f"
]

print("公式数量：", len(formulas))
print("前10个公式：")
for address, formula in formulas[:10]:
    print(address, formula)

book.close()

公式数量： 54
前10个公式：
Q7 =IF(ISBLANK(O7),IF(ISBLANK(M7),IF(ISBLANK(K7),IF(ISBLANK(I7),IF(ISBLANK(G7),IF(ISBLANK(E7),0,1),2),3),4),5),6)
AG7 =IF(ISBLANK(AE7),IF(ISBLANK(AC7),IF(ISBLANK(AA7),IF(ISBLANK(Y7),IF(ISBLANK(W7),IF(ISBLANK(U7),0,1),2),3),4),5),6)
Q10 =IF(ISBLANK(C10),0,Q7)
AG10 =IF(ISBLANK(S10),0,AG7)
Q12 =IF(ISBLANK(C12),0,Q7)
AG12 =IF(ISBLANK(S12),0,AG7)
Q14 =IF(ISBLANK(C14),0,Q7)
AG14 =IF(ISBLANK(S14),0,AG7)
Q16 =IF(ISBLANK(C16),0,Q7)
AG16 =IF(ISBLANK(S16),0,AG7)

In [13]:
extra_book = pd.ExcelFile(data_dir / "8.xlsx")
print(extra_book.sheet_names)

['Sensory thresholds', 'Sensory names', 'GBM importance MDI', 'GBM SHAP Values', 'Calibrated chemical dataset', 'Beer Prices', 'Sheet2']

In [14]:
for name in ["Sensory names", "Sheet2"]:
    table = pd.read_excel(extra_book, sheet_name=name, header=None)

    # 去掉全空的行、列，让输出更紧凑
    table = table.dropna(how="all").dropna(axis=1, how="all")

    print(f"\n工作表：{name}，大小：{table.shape}")
    print(table.head(12).to_string(index=False, header=False))

工作表：Sensory names，大小：(102, 8)
      dataset          R_name Category_Paper Category       CleanName_Paper         CleanName_PaperLong     CleanName_PanelFeedback    DataType
Trained panel    A_esters_all          Aroma    Yeast      Esters - overall                Esters aroma      Esters aroma - overall     numeric
Trained panel  A_esters_ethac          Aroma    Yeast  Esters - nail polish  Esters aroma - nail polish  Esters aroma - nail polish categorical
Trained panel A_esters_flower          Aroma    Yeast       Esters - floral       Esters aroma - floral       Esters aroma - floral categorical
Trained panel A_esters_fruity          Aroma    Yeast       Esters - fruity       Esters aroma - fruity       Esters aroma - fruity categorical
Trained panel  A_esters_isoaa          Aroma    Yeast       Esters - banana       Esters aroma - banana       Esters aroma - banana categorical
Trained panel      A_hops_all          Aroma     Hops        Hops - overall                  Hops aroma        Hops aroma - overall     numeric
Trained panel   A_hops_citrus          Aroma     Hops         Hops - citrus         Hops aroma - citrus         Hops aroma - citrus categorical
Trained panel    A_hops_noble          Aroma     Hops         Hops - grassy         Hops aroma - grassy         Hops aroma - grassy categorical
Trained panel A_hops_tropical          Aroma     Hops Hops - tropical fruit Hops aroma - tropical fruit Hops aroma - tropical fruit categorical
Trained panel    A_hops_woody          Aroma     Hops          Hops - woody          Hops aroma - woody          Hops aroma - woody categorical
Trained panel      A_malt_all          Aroma     Malt        Malt - overall                  Malt aroma        Malt aroma - overall     numeric

工作表：Sheet2，大小：(0, 0)
Empty DataFrame
Columns: []
Index: []

In [15]:
# 默认将第一行作为列名
sensory_dict = pd.read_excel(extra_book, sheet_name="Sensory names")

# 只取与当前50项评分对应的字典记录
target_info = sensory_dict.loc[
    sensory_dict["R_name"].isin(Y.columns),
    ["R_name", "Category_Paper", "CleanName_PaperLong", "DataType"]
]

print("匹配记录数：", len(target_info))
print("\n类型统计：")
print(target_info["DataType"].value_counts().to_string())

print("\n字段对应：")
print(target_info.to_string(index=False))

print("\n未匹配字段：")
print(Y.columns[~Y.columns.isin(target_info["R_name"])].tolist())

print("\n字典中重复的字段名：")
print(
    target_info.loc[
        target_info["R_name"].duplicated(keep=False), "R_name"
    ].tolist()
)

匹配记录数： 50

类型统计：
DataType
numeric        26
categorical    24

字段对应：
         R_name Category_Paper         CleanName_PaperLong    DataType
   A_esters_all          Aroma                Esters aroma     numeric
 A_esters_ethac          Aroma  Esters aroma - nail polish categorical
A_esters_flower          Aroma       Esters aroma - floral categorical
A_esters_fruity          Aroma       Esters aroma - fruity categorical
 A_esters_isoaa          Aroma       Esters aroma - banana categorical
     A_hops_all          Aroma                  Hops aroma     numeric
  A_hops_citrus          Aroma         Hops aroma - citrus categorical
   A_hops_noble          Aroma         Hops aroma - grassy categorical
A_hops_tropical          Aroma Hops aroma - tropical fruit categorical
   A_hops_woody          Aroma          Hops aroma - woody categorical
     A_malt_all          Aroma                  Malt aroma     numeric
   A_malt_bread          Aroma          Malt aroma - bread categorical
    A_malt_burn          Aroma         Malt aroma - smoked categorical
    A_malt_cara          Aroma        Malt aroma - caramel categorical
   A_malt_grain          Aroma          Malt aroma - grain categorical
   F_esters_all          Taste                Esters taste     numeric
 F_esters_ethac          Taste  Esters taste - nail polish categorical
F_esters_flower          Taste       Esters taste - floral categorical
F_esters_fruity          Taste       Esters taste - fruity categorical
 F_esters_isoaa          Taste       Esters taste - banana categorical
     F_hops_all          Taste                  Hops taste     numeric
  F_hops_citrus          Taste         Hops taste - citrus categorical
   F_hops_noble          Taste         Hops taste - grassy categorical
F_hops_tropical          Taste Hops taste - tropical fruit categorical
   F_hops_woody          Taste          Hops taste - woody categorical
     F_malt_all          Taste                  Malt taste     numeric
   F_malt_bread          Taste          Malt taste - bread categorical
    F_malt_burn          Taste         Malt taste - smoked categorical
    F_malt_cara          Taste        Malt taste - caramel categorical
   F_malt_grain          Taste          Malt taste - grain categorical
           X4vg          Taste            4-vinyl guaiacol     numeric
         acetic          Taste                 Acetic acid     numeric
        acidity          Taste                     Acidity     numeric
     aftertaste         Palate                  Aftertaste     numeric
        alcohol         Palate                     Alcohol     numeric
       barnyard          Taste                    Barnyard     numeric
      bitternes          Taste                  Bitterness     numeric
           body         Palate               Body fullness     numeric
          clove          Taste                       Clove     numeric
            co2         Palate                 Carbonation     numeric
      coriander          Taste                   Coriander     numeric
       diacetyl          Taste                    Diacetyl     numeric
            dms          Taste            Dimethyl sulfide     numeric
         lactic          Taste                 Lactic acid     numeric
       metallic          Taste                    Metallic     numeric
         orange          Taste         Hops taste - citrus     numeric
        overall        Overall        Overall appreciation     numeric
     stale_hops          Taste                  Stale hops     numeric
      sweetness          Taste                   Sweetness     numeric
            t2n          Taste     Aging aroma - cardboard     numeric

未匹配字段：
[]

字典中重复的字段名：
[]

In [17]:
from openpyxl import load_workbook

book = load_workbook(data_dir / "3.xlsx", data_only=False)
sheet = book["beer_1"]

for address in ["C10", "Q10", "S10", "AG10"]:
    cell = sheet[address]
    print(
        address,
        "内容：", cell.value,
        "批注：", cell.comment.text if cell.comment else "无"
    )

print("\n数据验证规则：")
for rule in sheet.data_validations.dataValidation:
    print(
        "范围：", rule.sqref,
        "类型：", rule.type,
        "条件：", rule.formula1
    )

book.close()

C10 内容： None 批注： 无
Q10 内容： =IF(ISBLANK(C10),0,Q7) 批注： 无
S10 内容： None 批注： 无
AG10 内容： =IF(ISBLANK(S10),0,AG7) 批注： 无

数据验证规则：

In [19]:
y = Y["A_malt_all"]

print("输入形状：", X.shape)
print("目标形状：", y.shape)
print("\n前5款啤酒的目标值：")
print(y.head())
print("\n输入与目标的编号顺序一致：", X.index.equals(y.index))

输入形状： (250, 231)
目标形状： (250,)

前5款啤酒的目标值：
beer
1    0.574178
2   -0.135865
3   -0.410904
4    0.213166
5    0.637144
Name: A_malt_all, dtype: float64

输入与目标的编号顺序一致： True

In [22]:
from sklearn.model_selection import train_test_split

# 风格仅用于平衡分组，暂不作为预测输入
styles = chem_aligned["tasting_category_fine"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=styles
)

print("训练集：", X_train.shape, y_train.shape)
print("测试集：", X_test.shape, y_test.shape)
print("两组重叠编号数：",
      len(X_train.index.intersection(X_test.index)))

训练集： (200, 231) (200,)
测试集： (50, 231) (50,)
两组重叠编号数： 0

In [23]:
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

baseline = DummyRegressor(strategy="mean")
baseline.fit(X_train, y_train)

pred_baseline = baseline.predict(X_test)

baseline_mae = mean_absolute_error(y_test, pred_baseline)
baseline_rmse = mean_squared_error(y_test, pred_baseline) ** 0.5
baseline_r2 = r2_score(y_test, pred_baseline)

print(f"训练集平均分：{y_train.mean():.3f}")
print(f"MAE：{baseline_mae:.3f}")
print(f"RMSE：{baseline_rmse:.3f}")
print(f"R²：{baseline_r2:.3f}")

训练集平均分：0.006
MAE：0.562
RMSE：0.742
R²：-0.045

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score, KFold

ridge_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("ridge", Ridge(alpha=10.0))
])

cv = KFold(n_splits=5, shuffle=True, random_state=42)

cv_mae = -cross_val_score(
    ridge_model,
    X_train,
    y_train,
    cv=cv,
    scoring="neg_mean_absolute_error"
)

baseline_cv_mae = -cross_val_score(
    baseline,
    X_train,
    y_train,
    cv=cv,
    scoring="neg_mean_absolute_error"
)

print("各折岭回归 MAE：", cv_mae.round(3))
print(f"岭回归平均 MAE：{cv_mae.mean():.3f}")
print(f"基准平均 MAE：{baseline_cv_mae.mean():.3f}")

各折岭回归 MAE： [0.773 2.094 0.487 0.682 0.506]
岭回归平均 MAE：0.908
基准平均 MAE：0.562

In [25]:
from sklearn.base import clone
import numpy as np

fold_results = []

for fold, (train_idx, valid_idx) in enumerate(cv.split(X_train), start=1):
    model = clone(ridge_model)

    X_fit = X_train.iloc[train_idx]
    X_valid = X_train.iloc[valid_idx]
    y_fit = y_train.iloc[train_idx]
    y_valid = y_train.iloc[valid_idx]

    model.fit(X_fit, y_fit)
    pred = model.predict(X_valid)

    errors = np.abs(y_valid.to_numpy() - pred)
    worst = int(errors.argmax())

    fold_results.append({
        "折数": fold,
        "MAE": errors.mean(),
        "最大绝对误差": errors.max(),
        "预测最小值": pred.min(),
        "预测最大值": pred.max(),
        "最差样本beer": y_valid.index[worst],
        "该样本真实值": y_valid.iloc[worst],
        "该样本预测值": pred[worst]
    })

print(pd.DataFrame(fold_results).round(3).to_string(index=False))

 折数   MAE  最大绝对误差   预测最小值  预测最大值  最差样本beer  该样本真实值  该样本预测值
  1 0.773   6.914  -0.793  6.378       177  -1.126   5.789
  2 2.094  66.647 -67.216  1.638       156  -0.569 -67.216
  3 0.487   1.205  -1.069  1.428        58  -0.937   0.267
  4 0.682   3.512  -1.234  3.913       130   0.401   3.913
  5 0.506   1.574  -1.598  1.087       231   2.661   1.087

In [26]:
# 取出第二折，划分方式与前面保持一致
train_idx, valid_idx = list(cv.split(X_train))[1]

model = clone(ridge_model)
model.fit(X_train.iloc[train_idx], y_train.iloc[train_idx])

# 取156号啤酒，按这一折训练得到的规则填补、标准化
sample = X_train.loc[[156]]
filled = model.named_steps["imputer"].transform(sample)
scaled = model.named_steps["scaler"].transform(filled)[0]

feature_names = model.named_steps["imputer"].get_feature_names_out()
coef = model.named_steps["ridge"].coef_

check = pd.DataFrame({
    "字段": feature_names,
    "标准化后的值": scaled,
    "回归系数": coef,
    "预测贡献": scaled * coef
})

check["贡献绝对值"] = check["预测贡献"].abs()

print(
    check.sort_values("贡献绝对值", ascending=False)
    .head(10)
    .round(4)
    .to_string(index=False)
)
print("模型截距：", model.named_steps["ridge"].intercept_)

                            字段    标准化后的值    回归系数     预测贡献   贡献绝对值
X2.methyltetrahydrofuran.3.one 1831.2281 -0.0365 -66.7790 66.7790
                     SO2.mg.L.   -2.2682 -0.1208   0.2741  0.2741
                           GFS   -2.1749  0.1043  -0.2269  0.2269
      X2.methylbutyl.octanoate   -3.7737  0.0574  -0.2167  0.2167
                            pH   -1.2486  0.1699  -0.2121  0.2121
             X.E..alpha.ionone    2.6542 -0.0764  -0.2028  0.2028
           caryophyllene.oxide   -1.9103  0.0913  -0.1744  0.1744
             beta.phellandrene    0.9942 -0.1519  -0.1510  0.1510
             X2.butyloctanoate   -2.4545 -0.0563   0.1381  0.1381
            neryl.isobutanoate   -3.1249  0.0429  -0.1340  0.1340
模型截距： 0.028890347018750397

In [27]:
feature = "X2.methyltetrahydrofuran.3.one"

train_values = X_train.iloc[train_idx][feature]

print("第二折训练部分的统计：")
print(train_values.describe().to_string())

print("\n不同取值数量：", train_values.nunique())
print("\n最常见的5个值：")
print(train_values.value_counts().head().to_string())

print("\n156号的值：", X_train.loc[156, feature])

# 查看模型实际使用的标准化参数
position = list(feature_names).index(feature)
scaler = model.named_steps["scaler"]

print("模型使用的均值：", scaler.mean_[position])
print("模型使用的缩放尺度：", scaler.scale_[position])

第二折训练部分的统计：
count    160.000000
mean       1.149515
std        6.899648
min        0.000564
25%        0.023517
50%        0.049939
75%        0.095092
max       76.832805

不同取值数量： 160

最常见的5个值：
X2.methyltetrahydrofuran.3.one
0.086493     1
13.022444    1
0.010823     1
0.070937     1
0.068434     1

156号的值： 12596.43287
模型使用的均值： 1.1495146708250001
模型使用的缩放尺度： 6.878052568176043

In [28]:
calibrated = pd.read_excel(
    extra_book,
    sheet_name="Calibrated chemical dataset"
)

print("表格大小：", calibrated.shape)
print("\n前15个列名：")
print(calibrated.columns[:15].tolist())

print("\n包含目标名称的列：")
print([
    col for col in calibrated.columns
    if "tetrahydrofuran" in str(col).lower()
])

print("\n前3行、前6列：")
print(calibrated.iloc[:3, :6].to_string(index=False))

表格大小： (250, 73)

前15个列名：
['beer', 'beer_id', 'tasting_category_fine', 'acetaldehyde', 'CS2', 'DES', 'DMS', 'ethyl_2.methyl_butyrate', 'ethyl_acetate', 'ethyl_decanoate', 'ethyl_hexanoate', 'ethyl_isovalerate', 'ethyl_octanoate', 'ethyl_propionate', 'H2S']

包含目标名称的列：
['X2.methyltetrahydrofuran.3.one']

前3行、前6列：
 beer       beer_id tasting_category_fine  acetaldehyde  CS2      DES
   10 5410228202929        Low/No alcohol      0.228170  0.0 0.000000
   86 5410783031019        Low/No alcohol      0.668615  0.0 0.553225
    2 5410228142003        Low/No alcohol      3.243895  0.0 0.000000

In [29]:
feature = "X2.methyltetrahydrofuran.3.one"

# 按啤酒编号对齐两份数据
comparison = (
    chem.set_index("beer")[[feature]]
    .rename(columns={feature: "附件1"})
    .join(
        calibrated.set_index("beer")[[feature]]
        .rename(columns={feature: "附件8"}),
        how="inner",
        validate="one_to_one"
    )
)

# 沿用第二折训练部分的编号
train_beers = X_train.iloc[train_idx].index
train_comparison = comparison.loc[train_beers]

print("156号在两份数据中的值：")
print(comparison.loc[[156]].to_string())

print("\n第二折训练部分，附件1数值最大的5款：")
print(
    train_comparison.sort_values("附件1", ascending=False)
    .head(5)
    .to_string()
)

print("\n第二折训练部分，两列的统计：")
print(train_comparison.describe().to_string())

156号在两份数据中的值：
              附件1           附件8
beer
156   12596.43287  12596.432872

第二折训练部分，附件1数值最大的5款：
            附件1        附件8
beer
177   76.832805  76.832805
118   26.828259  26.828259
7     23.349785  23.349785
181   19.235231  19.235231
73    13.022444  13.022444

第二折训练部分，两列的统计：
              附件1         附件8
count  160.000000  160.000000
mean     1.149515    1.149515
std      6.899648    6.899648
min      0.000564    0.000564
25%      0.023517    0.023517
50%      0.049939    0.049939
75%      0.095092    0.095092
max     76.832805   76.832805

In [30]:
from sklearn.preprocessing import FunctionTransformer

feature = "X2.methyltetrahydrofuran.3.one"

def log_selected_column(data):
    result = data.copy()
    if (result[feature].dropna() < 0).any():
        raise ValueError("目标列存在负数，需要先核查")
    result[feature] = np.log1p(result[feature])
    return result

ridge_log_model = Pipeline([
    ("log", FunctionTransformer(log_selected_column)),
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("ridge", Ridge(alpha=10.0))
])

log_cv_mae = -cross_val_score(
    ridge_log_model,
    X_train,
    y_train,
    cv=cv,
    scoring="neg_mean_absolute_error"
)

print("变换后各折 MAE：", log_cv_mae.round(3))
print(f"变换后平均 MAE：{log_cv_mae.mean():.3f}")
print(f"原岭回归平均 MAE：{cv_mae.mean():.3f}")
print(f"基准平均 MAE：{baseline_cv_mae.mean():.3f}")

变换后各折 MAE： [0.773 0.438 0.489 0.685 0.511]
变换后平均 MAE：0.579
原岭回归平均 MAE：0.908
基准平均 MAE：0.562

In [31]:
from sklearn.model_selection import GridSearchCV

search = GridSearchCV(
    estimator=ridge_log_model,
    param_grid={"ridge__alpha": [1, 10, 100, 1000, 10000]},
    scoring="neg_mean_absolute_error",
    cv=cv,
    n_jobs=-1
)

search.fit(X_train, y_train)

results = pd.DataFrame({
    "alpha": [
        params["ridge__alpha"]
        for params in search.cv_results_["params"]
    ],
    "平均MAE": -search.cv_results_["mean_test_score"],
    "各折MAE标准差": search.cv_results_["std_test_score"]
})

print(results.round(3).to_string(index=False))
print("\n最佳参数：", search.best_params_)
print(f"基准平均MAE：{baseline_cv_mae.mean():.3f}")

 alpha  平均MAE  各折MAE标准差
     1  0.769     0.125
    10  0.579     0.128
   100  0.463     0.095
  1000  0.473     0.068
 10000  0.533     0.066

最佳参数： {'ridge__alpha': 100}
基准平均MAE：0.562

In [32]:
# GridSearchCV 默认已用最佳参数在全部200款训练样本上重新训练
best_model = search.best_estimator_

pred_test = best_model.predict(X_test)

comparison = pd.DataFrame({
    "模型": ["均值基准", "岭回归"],
    "MAE": [
        baseline_mae,
        mean_absolute_error(y_test, pred_test)
    ],
    "RMSE": [
        baseline_rmse,
        mean_squared_error(y_test, pred_test) ** 0.5
    ],
    "R²": [
        baseline_r2,
        r2_score(y_test, pred_test)
    ]
})

print(comparison.round(3).to_string(index=False))

  模型   MAE  RMSE     R²
均值基准 0.562 0.742 -0.045
 岭回归 0.480 0.727 -0.002

In [33]:
from sklearn.model_selection import cross_val_predict

# 固定alpha=100，重新得到每款训练啤酒的折外预测
oof_pred = cross_val_predict(
    clone(best_model),
    X_train,
    y_train,
    cv=cv
)

errors = pd.DataFrame({
    "真实值": y_train,
    "折外预测": oof_pred
})

errors["绝对误差"] = (
    errors["真实值"] - errors["折外预测"]
).abs()

print("误差最大的10款：")
print(
    errors.sort_values("绝对误差", ascending=False)
    .head(10)
    .round(3)
    .to_string()
)

print("\n绝对误差分布：")
print(
    errors["绝对误差"]
    .quantile([0.5, 0.9, 0.95, 1.0])
    .round(3)
)

误差最大的10款：
        真实值   折外预测   绝对误差
beer
177  -1.126  3.182  4.307
130   0.401  2.840  2.439
103   2.876  4.647  1.771
231   2.661  0.941  1.720
168   1.419 -0.064  1.483
117   2.081  0.600  1.480
134   1.448  0.117  1.331
74    1.157 -0.163  1.320
86    1.678  0.473  1.205
105   1.770  0.568  1.202

绝对误差分布：
0.50    0.340
0.90    0.903
0.95    1.114
1.00    4.307
Name: 绝对误差, dtype: float64

In [34]:
suspects = [177, 130]

for fold, (train_idx, valid_idx) in enumerate(cv.split(X_train), start=1):
    valid_beers = X_train.iloc[valid_idx].index
    selected = [beer for beer in suspects if beer in valid_beers]

    if not selected:
        continue

    model = clone(best_model)
    model.fit(
        X_train.iloc[train_idx],
        y_train.iloc[train_idx]
    )

    for beer in selected:
        sample = X_train.loc[[beer]]

        # 执行模型前面的全部处理：log1p、填补、标准化
        transformed = model[:-1].transform(sample)[0]
        coefficients = model.named_steps["ridge"].coef_
        names = model.named_steps["imputer"].get_feature_names_out()

        contributions = pd.DataFrame({
            "字段": names,
            "标准化值": transformed,
            "预测贡献": transformed * coefficients
        })
        contributions["贡献绝对值"] = contributions["预测贡献"].abs()

        print(f"\n第{fold}折，beer={beer}")
        print(f"真实值：{y_train.loc[beer]:.3f}")
        print(f"预测值：{model.predict(sample)[0]:.3f}")
        print(
            contributions.sort_values("贡献绝对值", ascending=False)
            .head(5)
            .round(3)
            .to_string(index=False)
        )

第1折，beer=177
真实值：-1.126
预测值：3.182
              字段   标准化值   预测贡献  贡献绝对值
  methylpyrazine 60.602  3.710  3.710
         eugenol 15.063  0.647  0.647
   hexyl.acetate 27.145 -0.497  0.497
  alpha.humulene 20.012  0.396  0.396
ethyl.pentanoate 11.183 -0.295  0.295

第4折，beer=130
真实值：0.401
预测值：2.840
                       字段   标准化值  预测贡献  贡献绝对值
        X5.methylfurfural 35.855 1.776  1.776
                 furfural 19.433 0.536  0.536
X2.ethyl.3.methylpyrazine 16.634 0.428  0.428
       phenylacetaldehyde 13.850 0.256  0.256
        gamma.nonalactone 11.796 0.228  0.228

In [35]:
# 只检查200款训练数据，保留测试集
distribution = pd.DataFrame({
    "最小值": X_train.min(),
    "中位数": X_train.median(),
    "95%分位数": X_train.quantile(0.95),
    "最大值": X_train.max(),
    "偏度": X_train.skew(),
    "负值数量": (X_train < 0).sum()
})

print("偏度最高的15列：")
print(
    distribution.sort_values("偏度", ascending=False)
    .head(15)
    .round(3)
    .to_string()
)

print("\n本次重点关注的两列：")
print(
    distribution.loc[["methylpyrazine", "X5.methylfurfural"]]
    .round(3)
    .to_string()
)

偏度最高的15列：
                                  最小值    中位数  95%分位数        最大值      偏度  负值数量
X2.methyltetrahydrofuran.3.one  0.001  0.050   0.637  12596.433  14.141     0
E.caryophyllene                 0.000  0.001   0.159     40.927  12.465     0
hexyl.acetate                   0.000  0.055   0.413     10.808  11.279     0
X3.methylbutanal                0.000  0.105   0.967    127.059  10.441     0
alpha.humulene                  0.001  0.012   0.086      5.263  10.380     0
gamma.nonalactone               0.000  0.412   3.864   7256.136   9.909     0
X.E..2.nonenal                  0.000  0.012   0.142     10.960   9.828     0
methylpyrazine                  0.000  0.000   0.014      0.896   9.537     0
X5.methylfurfural               0.000  0.001   0.004      0.040   9.365     0
X.E..beta.ocimene               0.000  0.012   0.090      1.519   9.207     0
X3Z.hexenol                     0.001  0.024   0.121      3.423   9.170     0
eugenol                         0.000  0.002   0.314      3.568   8.311     0
ethyl.pentanoate                0.004  0.025   0.056      1.679   8.279     0
furfural                        0.000  0.008   0.147      1.819   7.946     0
styrene                         0.000  0.041   0.318      2.931   7.765     0

本次重点关注的两列：
                   最小值    中位数  95%分位数    最大值     偏度  负值数量
methylpyrazine     0.0  0.000   0.014  0.896  9.537     0
X5.methylfurfural  0.0  0.001   0.004  0.040  9.365     0

In [36]:
from sklearn.base import BaseEstimator, TransformerMixin

class QuantileClipper(BaseEstimator, TransformerMixin):
    def __init__(self, lower=0.01, upper=0.99):
        self.lower = lower
        self.upper = upper

    def fit(self, X, y=None):
        values = np.asarray(X, dtype=float)
        self.lower_bounds_ = np.nanquantile(values, self.lower, axis=0)
        self.upper_bounds_ = np.nanquantile(values, self.upper, axis=0)
        return self

    def transform(self, X):
        values = np.asarray(X, dtype=float)
        return np.clip(values, self.lower_bounds_, self.upper_bounds_)

# 保留已有对数处理和alpha，只增加缩尾，方便比较
ridge_clip_model = Pipeline([
    ("log", FunctionTransformer(log_selected_column)),
    ("clip", QuantileClipper()),
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("ridge", Ridge(alpha=100))
])

clip_mae = -cross_val_score(
    ridge_clip_model,
    X_train,
    y_train,
    cv=cv,
    scoring="neg_mean_absolute_error"
)

print("缩尾后各折MAE：", clip_mae.round(3))
print(f"缩尾后平均MAE：{clip_mae.mean():.3f}")
print(f"各折MAE标准差：{clip_mae.std():.3f}")
print("未缩尾、alpha=100的平均MAE：约0.463")

缩尾后各折MAE： [0.464 0.323 0.411 0.469 0.44 ]
缩尾后平均MAE：0.421
各折MAE标准差：0.053
未缩尾、alpha=100的平均MAE：约0.463

In [37]:
from sklearn.model_selection import RepeatedKFold

repeat_cv = RepeatedKFold(
    n_splits=5,
    n_repeats=3,
    random_state=2026
)

models = {
    "均值基准": baseline,
    "未缩尾岭回归": best_model,
    "缩尾岭回归": ridge_clip_model
}

repeat_scores = {}

for name, estimator in models.items():
    scores = -cross_val_score(
        estimator,
        X_train,
        y_train,
        cv=repeat_cv,
        scoring="neg_mean_absolute_error"
    )
    repeat_scores[name] = scores

summary = pd.DataFrame({
    name: {
        "平均MAE": scores.mean(),
        "各折标准差": scores.std()
    }
    for name, scores in repeat_scores.items()
}).T

print(summary.round(3).to_string())

improvement = (
    repeat_scores["未缩尾岭回归"]
    - repeat_scores["缩尾岭回归"]
)
print("\n缩尾优于未缩尾的折数：",
      (improvement > 0).sum(), "/ 15")

        平均MAE  各折标准差
均值基准    0.561  0.051
未缩尾岭回归  0.461  0.076
缩尾岭回归   0.422  0.043

缩尾优于未缩尾的折数： 13 / 15

In [38]:
# 只去掉单列log1p，其他设置保持一致
clip_only_model = Pipeline([
    ("clip", QuantileClipper()),
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("ridge", Ridge(alpha=100))
])

clip_only_mae = -cross_val_score(
    clip_only_model,
    X_train,
    y_train,
    cv=repeat_cv,
    scoring="neg_mean_absolute_error"
)

with_log_mae = repeat_scores["缩尾岭回归"]

print(f"对数＋缩尾：{with_log_mae.mean():.4f}")
print(f"仅缩尾：{clip_only_mae.mean():.4f}")
print(f"仅缩尾的各折标准差：{clip_only_mae.std():.4f}")

print("仅缩尾更好的折数：",
      (clip_only_mae < with_log_mae).sum(), "/ 15")

对数＋缩尾：0.4220
仅缩尾：0.4222
仅缩尾的各折标准差：0.0433
仅缩尾更好的折数： 4 / 15

In [40]:
selected_model = clone(clip_only_model)

In [41]:
aroma_cols = [col for col in Y.columns if col.startswith("A_")]
flavour_cols = [col for col in Y.columns if col.startswith("F_")]

print("香气指标数量：", len(aroma_cols))
print(aroma_cols)

print("\n风味指标数量：", len(flavour_cols))
print(flavour_cols)

other_cols = [
    col for col in Y.columns
    if col not in aroma_cols + flavour_cols
]
print("\n其他感官指标：", other_cols)

香气指标数量： 15
['A_malt_all', 'A_malt_grain', 'A_malt_bread', 'A_malt_cara', 'A_malt_burn', 'A_hops_all', 'A_hops_citrus', 'A_hops_tropical', 'A_hops_noble', 'A_hops_woody', 'A_esters_all', 'A_esters_ethac', 'A_esters_isoaa', 'A_esters_flower', 'A_esters_fruity']

风味指标数量： 15
['F_malt_all', 'F_malt_grain', 'F_malt_bread', 'F_malt_cara', 'F_malt_burn', 'F_hops_all', 'F_hops_citrus', 'F_hops_tropical', 'F_hops_noble', 'F_hops_woody', 'F_esters_all', 'F_esters_ethac', 'F_esters_isoaa', 'F_esters_flower', 'F_esters_fruity']

其他感官指标： ['acidity', 'bitternes', 'sweetness', 'X4vg', 'diacetyl', 'dms', 'metallic', 'stale_hops', 't2n', 'orange', 'coriander', 'clove', 'lactic', 'acetic', 'barnyard', 'alcohol', 'aftertaste', 'body', 'co2', 'overall']

In [42]:
target_cols = aroma_cols + flavour_cols

# 用编号选取目标，保证与X_train逐行对应
Y_train = Y.loc[X_train.index, target_cols]

rows = []

for target in target_cols:
    target_y = Y_train[target]

    base_mae = -cross_val_score(
        DummyRegressor(strategy="mean"),
        X_train, target_y,
        cv=cv,
        scoring="neg_mean_absolute_error"
    ).mean()

    model_mae = -cross_val_score(
        selected_model,
        X_train, target_y,
        cv=cv,
        scoring="neg_mean_absolute_error"
    ).mean()

    rows.append({
        "指标": target,
        "基准MAE": base_mae,
        "模型MAE": model_mae,
        "改善率%": (
            (base_mae - model_mae) / base_mae * 100
            if base_mae > 0 else float("nan")
        )
    })

target_results = pd.DataFrame(rows).sort_values("改善率%")

print(target_results.round(3).to_string(index=False))
print(
    "\n优于基准的指标数量：",
    (target_results["改善率%"] > 0).sum(),
    "/", len(target_results)
)

             指标  基准MAE  模型MAE    改善率%
A_hops_tropical  0.400  0.449 -12.413
F_hops_tropical  0.360  0.397 -10.265
    A_malt_burn  0.379  0.407  -7.392
A_esters_fruity  0.362  0.388  -7.157
   F_malt_grain  0.365  0.387  -6.154
F_esters_flower  0.295  0.302  -2.563
   A_hops_woody  0.293  0.297  -1.620
   F_hops_woody  0.352  0.356  -1.321
  A_hops_citrus  0.380  0.384  -1.066
  F_hops_citrus  0.348  0.351  -0.889
F_esters_fruity  0.372  0.373  -0.365
A_esters_flower  0.329  0.327   0.625
   A_malt_grain  0.346  0.343   0.933
 F_esters_isoaa  0.435  0.431   0.948
 A_esters_isoaa  0.423  0.414   2.010
   A_malt_bread  0.380  0.369   2.949
 A_esters_ethac  0.401  0.381   4.923
   A_esters_all  0.475  0.441   7.037
    F_malt_burn  0.449  0.416   7.273
 F_esters_ethac  0.394  0.361   8.264
    F_malt_cara  0.419  0.383   8.564
   A_hops_noble  0.434  0.383  11.632
     A_hops_all  0.534  0.464  13.247
   F_esters_all  0.470  0.404  13.902
   F_malt_bread  0.378  0.321  14.937
    A_malt_cara  0.456  0.365  20.099
   F_hops_noble  0.493  0.389  21.097
     F_hops_all  0.581  0.444  23.503
     A_malt_all  0.562  0.422  24.844
     F_malt_all  0.551  0.403  26.888

优于基准的指标数量： 19 / 30

In [43]:
from sklearn.ensemble import RandomForestRegressor

forest_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("forest", RandomForestRegressor(
        n_estimators=200,
        max_depth=6,
        min_samples_leaf=5,
        max_features=0.7,
        random_state=42,
        n_jobs=-1
    ))
])

forest_scores = {}

for target in target_cols:
    mae = -cross_val_score(
        forest_model,
        X_train,
        Y_train[target],
        cv=cv,
        scoring="neg_mean_absolute_error"
    ).mean()

    forest_scores[target] = mae

model_comparison = target_results.copy()
model_comparison["森林MAE"] = (
    model_comparison["指标"].map(forest_scores)
)
model_comparison["森林改善率%"] = (
    1 - model_comparison["森林MAE"] / model_comparison["基准MAE"]
) * 100

print(
    model_comparison.sort_values("森林改善率%", ascending=False)
    .round(3)
    .to_string(index=False)
)

print(
    "\n森林优于基准的指标数：",
    (model_comparison["森林改善率%"] > 0).sum(), "/ 30"
)

             指标  基准MAE  模型MAE    改善率%  森林MAE  森林改善率%
     F_hops_all  0.581  0.444  23.503  0.404  30.486
   F_hops_noble  0.493  0.389  21.097  0.366  25.726
     F_malt_all  0.551  0.403  26.888  0.425  22.840
     A_hops_all  0.534  0.464  13.247  0.417  21.967
    F_malt_burn  0.449  0.416   7.273  0.361  19.601
   A_hops_noble  0.434  0.383  11.632  0.350  19.397
     A_malt_all  0.562  0.422  24.844  0.456  18.767
    A_malt_cara  0.456  0.365  20.099  0.376  17.677
   F_esters_all  0.470  0.404  13.902  0.391  16.689
    F_malt_cara  0.419  0.383   8.564  0.352  16.028
   F_malt_bread  0.378  0.321  14.937  0.322  14.648
 F_esters_ethac  0.394  0.361   8.264  0.343  12.838
    A_malt_burn  0.379  0.407  -7.392  0.338  10.847
   A_esters_all  0.475  0.441   7.037  0.427  10.034
 A_esters_ethac  0.401  0.381   4.923  0.365   8.994
  A_hops_citrus  0.380  0.384  -1.066  0.346   8.836
F_esters_fruity  0.372  0.373  -0.365  0.341   8.341
   F_hops_woody  0.352  0.356  -1.321  0.325   7.524
  F_hops_citrus  0.348  0.351  -0.889  0.323   7.330
   A_malt_bread  0.380  0.369   2.949  0.353   7.149
   A_hops_woody  0.293  0.297  -1.620  0.275   6.014
 A_esters_isoaa  0.423  0.414   2.010  0.398   5.839
F_hops_tropical  0.360  0.397 -10.265  0.344   4.440
 F_esters_isoaa  0.435  0.431   0.948  0.417   4.192
A_hops_tropical  0.400  0.449 -12.413  0.393   1.740
A_esters_flower  0.329  0.327   0.625  0.324   1.638
F_esters_flower  0.295  0.302  -2.563  0.293   0.453
A_esters_fruity  0.362  0.388  -7.157  0.360   0.452
   A_malt_grain  0.346  0.343   0.933  0.346   0.119
   F_malt_grain  0.365  0.387  -6.154  0.371  -1.631

森林优于基准的指标数： 29 / 30

In [45]:
selection = model_comparison[
    ["指标", "基准MAE", "模型MAE", "森林MAE"]
].copy()

selection = selection.rename(columns={"模型MAE": "岭回归MAE"})

score_columns = ["基准MAE", "岭回归MAE", "森林MAE"]

selection["候选模型"] = (
    selection[score_columns]
    .idxmin(axis=1)
    .map({
        "基准MAE": "均值基准",
        "岭回归MAE": "岭回归",
        "森林MAE": "随机森林"
    })
)

print(selection.round(3).to_string(index=False))
print("\n候选模型数量：")
print(selection["候选模型"].value_counts())

             指标  基准MAE  岭回归MAE  森林MAE 候选模型
A_hops_tropical  0.400   0.449  0.393 随机森林
F_hops_tropical  0.360   0.397  0.344 随机森林
    A_malt_burn  0.379   0.407  0.338 随机森林
A_esters_fruity  0.362   0.388  0.360 随机森林
   F_malt_grain  0.365   0.387  0.371 均值基准
F_esters_flower  0.295   0.302  0.293 随机森林
   A_hops_woody  0.293   0.297  0.275 随机森林
   F_hops_woody  0.352   0.356  0.325 随机森林
  A_hops_citrus  0.380   0.384  0.346 随机森林
  F_hops_citrus  0.348   0.351  0.323 随机森林
F_esters_fruity  0.372   0.373  0.341 随机森林
A_esters_flower  0.329   0.327  0.324 随机森林
   A_malt_grain  0.346   0.343  0.346  岭回归
 F_esters_isoaa  0.435   0.431  0.417 随机森林
 A_esters_isoaa  0.423   0.414  0.398 随机森林
   A_malt_bread  0.380   0.369  0.353 随机森林
 A_esters_ethac  0.401   0.381  0.365 随机森林
   A_esters_all  0.475   0.441  0.427 随机森林
    F_malt_burn  0.449   0.416  0.361 随机森林
 F_esters_ethac  0.394   0.361  0.343 随机森林
    F_malt_cara  0.419   0.383  0.352 随机森林
   A_hops_noble  0.434   0.383  0.350 随机森林
     A_hops_all  0.534   0.464  0.417 随机森林
   F_esters_all  0.470   0.404  0.391 随机森林
   F_malt_bread  0.378   0.321  0.322  岭回归
    A_malt_cara  0.456   0.365  0.376  岭回归
   F_hops_noble  0.493   0.389  0.366 随机森林
     F_hops_all  0.581   0.444  0.404 随机森林
     A_malt_all  0.562   0.422  0.456  岭回归
     F_malt_all  0.551   0.403  0.425  岭回归

候选模型数量：
候选模型
随机森林    24
岭回归      5
均值基准     1
Name: count, dtype: int64

In [46]:
# 按编号对齐30项测试评分
Y_test = Y.loc[X_test.index, target_cols]

model_templates = {
    "均值基准": DummyRegressor(strategy="mean"),
    "岭回归": selected_model,  # 仅缩尾版本，alpha=100
    "随机森林": forest_model
}

test_rows = []
prediction_rows = []
fitted_models = {}

for _, row in selection.iterrows():
    target = row["指标"]
    model_name = row["候选模型"]

    model = clone(model_templates[model_name])
    model.fit(X_train, Y_train[target])
    pred = model.predict(X_test)
    fitted_models[target] = model

    # 每个指标都用它自己的训练均值作基准
    base = DummyRegressor(strategy="mean")
    base.fit(X_train, Y_train[target])
    base_pred = base.predict(X_test)

    actual = Y_test[target]
    base_mae = mean_absolute_error(actual, base_pred)
    mae = mean_absolute_error(actual, pred)

    test_rows.append({
        "指标": target,
        "模型": model_name,
        "测试基准MAE": base_mae,
        "测试MAE": mae,
        "测试RMSE": mean_squared_error(actual, pred) ** 0.5,
        "测试R²": r2_score(actual, pred),
        "测试改善率%": (
            (1 - mae / base_mae) * 100
            if base_mae > 0 else float("nan")
        )
    })

    prediction_rows.append(pd.DataFrame({
        "beer": X_test.index,
        "指标": target,
        "模型": model_name,
        "真实值": actual.to_numpy(),
        "预测值": pred,
        "基准预测值": base_pred
    }))

test_results = pd.DataFrame(test_rows)
test_predictions = pd.concat(prediction_rows, ignore_index=True)

# 保存到与data同级的outputs文件夹
output_dir = data_dir.resolve().parent / "outputs"
output_dir.mkdir(exist_ok=True)

selection.to_csv(
    output_dir / "model_selection_cv.csv",
    index=False, encoding="utf-8-sig"
)
test_results.to_csv(
    output_dir / "test_metrics.csv",
    index=False, encoding="utf-8-sig"
)
test_predictions.to_csv(
    output_dir / "test_predictions.csv",
    index=False, encoding="utf-8-sig"
)

print(test_results.round(3).to_string(index=False))
print("\n测试MAE优于基准的指标数：",
      (test_results["测试改善率%"] > 0).sum(), "/ 30")
print("结果保存位置：", output_dir)

             指标   模型  测试基准MAE  测试MAE  测试RMSE   测试R²  测试改善率%
A_hops_tropical 随机森林    0.288  0.278   0.374 -0.009   3.634
F_hops_tropical 随机森林    0.317  0.255   0.341  0.194  19.582
    A_malt_burn 随机森林    0.455  0.433   0.711  0.153   4.746
A_esters_fruity 随机森林    0.334  0.311   0.472  0.189   6.816
   F_malt_grain 均值基准    0.309  0.309   0.421 -0.006   0.000
F_esters_flower 随机森林    0.318  0.299   0.444  0.049   5.788
   A_hops_woody 随机森林    0.214  0.231   0.300 -0.252  -7.779
   F_hops_woody 随机森林    0.311  0.265   0.339  0.267  14.748
  A_hops_citrus 随机森林    0.350  0.335   0.421  0.046   4.153
  F_hops_citrus 随机森林    0.327  0.353   0.448 -0.336  -8.151
F_esters_fruity 随机森林    0.317  0.310   0.402  0.099   2.301
A_esters_flower 随机森林    0.335  0.302   0.358  0.164   9.818
   A_malt_grain  岭回归    0.344  0.373   0.495 -0.209  -8.725
 F_esters_isoaa 随机森林    0.374  0.304   0.398  0.358  18.582
 A_esters_isoaa 随机森林    0.422  0.349   0.412  0.311  17.337
   A_malt_bread 随机森林    0.338  0.347   0.530 -0.058  -2.815
 A_esters_ethac 随机森林    0.400  0.385   0.467  0.042   3.879
   A_esters_all 随机森林    0.486  0.387   0.461  0.408  20.228
    F_malt_burn 随机森林    0.481  0.377   0.561  0.332  21.682
 F_esters_ethac 随机森林    0.371  0.338   0.410  0.024   8.807
    F_malt_cara 随机森林    0.521  0.418   0.562  0.239  19.709
   A_hops_noble 随机森林    0.387  0.336   0.430  0.224  13.140
     A_hops_all 随机森林    0.435  0.383   0.507  0.169  12.021
   F_esters_all 随机森林    0.448  0.350   0.469  0.375  22.048
   F_malt_bread  岭回归    0.412  0.388   0.529  0.090   5.754
    A_malt_cara  岭回归    0.544  0.413   0.545  0.404  24.095
   F_hops_noble 随机森林    0.476  0.395   0.503  0.276  17.158
     F_hops_all 随机森林    0.533  0.392   0.465  0.491  26.534
     A_malt_all  岭回归    0.562  0.422   0.539  0.449  24.990
     F_malt_all  岭回归    0.581  0.405   0.494  0.505  30.353

测试MAE优于基准的指标数： 25 / 30
结果保存位置： C:\Users\Lenovo\PycharmProjects\PythonProject2\outputs

In [47]:
print("当前候选输入数量：", len(X.columns))

for i, name in enumerate(X.columns, start=1):
    print(f"{i:3d}. {name}")

当前候选输入数量： 231
  1. acetaldehyde
  2. CS2
  3. DES
  4. DMS
  5. ethyl_2.methyl_butyrate
  6. ethyl_acetate
  7. ethyl_decanoate
  8. ethyl_hexanoate
  9. ethyl_isovalerate
 10. ethyl_octanoate
 11. ethyl_propionate
 12. H2S
 13. isoamyl_alcohol
 14. isobutanol
 15. isobutyl_acetate
 16. isopentyl_acetate
 17. MeSH
 18. octyl_acetate
 19. phenethyl_acetate
 20. phenethyl_alcohol
 21. X4VG
 22. SO2.mg.L.
 23. acetic_acid.g.L.
 24. ammonia.mg.L.
 25. color.EBC.
 26. betaglucan.mg.L.
 27. lactic_acid.mg.L.
 28. glycerol
 29. iron
 30. pH
 31. protein.g.L.
 32. bitterness
 33. GFS
 34. ethanol..v.v.
 35. CO2.PSI.
 36. unfermentables
 37. kcalperc
 38. X1.propanol
 39. X2.3.butanedione
 40. X3.methylbutanal
 41. propylene.glycol
 42. propyl.acetate
 43. n.pentanol
 44. X2.methyl.1.butanol
 45. isopentyl.formate
 46. ethyl.isobutyrate
 47. X3.methyl.2.butenal
 48. X2.methyltetrahydrofuran.3.one
 49. ethyl.butyrate
 50. butyl.acetate
 51. methylpyrazine
 52. furfural
 53. ethyl.lactate
 54. X3Z.hexenol
 55. n.hexanol
 56. styrene
 57. X2.furanmethanol
 58. X3.methyl.2.hexanol
 59. X3.furanmethanol
 60. X2.acetylfuran
 61. X2.6.dimethyl.pyrazine
 62. amyl.acetate
 63. ethyl.tiglate
 64. benzaldehyde
 65. X5.methylfurfural
 66. n.heptanol
 67. X1.octen.3.ol
 68. X3.methylthio.propanol
 69. isomaltol
 70. X6.methyl.5.hepten.2.one
 71. X2.pentyl.furan
 72. ethyl.hex..3E..enoate
 73. alpha.phellandrene
 74. dehydroxy.cis.linalool.oxide
 75. hexyl.acetate
 76. isopentyl.butanoate
 77. X2.ethyl.1.hexanol
 78. beta.phellandrene
 79. limonene
 80. eucalyptol
 81. benzyl.alcohol
 82. ethyl.hex..2E..enoate
 83. phenylacetaldehyde
 84. X.E..beta.ocimene
 85. prenyl.isobutyrate
 86. ethyl.furoate
 87. ortho.cresol
 88. ethyl.5.methylhexanoate
 89. X2.acetylpyrrole
 90. isoamyl.lactate
 91. n.octanol
 92. cis.linalool.oxide
 93. meta.cymenene
 94. terpinolene
 95. linalool
 96. nonan.2.ol
 97. n.nonanal
 98. X2.methyl.benzofuran
 99. heptyl.acetate
100. X4.methyl.1.pentanol
101. neo.allo.ocimene
102. x.methyl.1.octanol
103. trans.dihydro.beta.terpineol
104. cis.beta.terpineol
105. y.methyl.1.octanol
106. camphor
107. isobutyl.hexanoate
108. nerol.oxide
109. X.E..2.nonenal
110. cis.dihydro.beta.terpineol
111. X4.ethyl.phenol
112. isoborneol
113. ethyl.benzoate
114. n.nonanol
115. terpinen.4.ol
116. diethyl.succinate
117. vinyl.caprylate
118. X1.alpha.terpineol
119. ethyl..E..linalool
120. ethyl.nicotinate
121. citronellol
122. nerol
123. hydroxy.methyl.furfural
124. E.ocimenone
125. cumin.aldehyde
126. ethyl.phenylacetate
127. isopentyl.hexanoate
128. geraniol
129. beta.cyclohomocitral
130. E.cinnamaldehyde
131. n.decanol
132. neryl.formate
133. X4.ethyl.guaiacol
134. X2.undecanone
135. trans.dihydro.alpha.terpinyl.acetate
136. terpinen.4.ol.acetate
137. X2.undecanol
138. delta.terpinyl.acetate
139. X.E.E..2.4.decadienal
140. methyl.geranate
141. car.3.en.2.one
142. dimethoxy..E..citral
143. X2.butyloctanoate
144. X4.methoxysalicylaldehyde
145. ethyl.hydrocinnamate
146. eugenol
147. gamma.nonalactone
148. methyl.para.anisate
149. X.E..beta.damascenone
150. ethyl..9..decenoate
151. vanillin
152. geosmin
153. dodecanal
154. X4.8.alpha.epoxy.caryophyllane
155. E.caryophyllene
156. X.E..alpha.ionone
157. perillyl.acetate
158. beta.humulene
159. X2.phenyl.ethyl.butyrate
160. X.Z..beta.farnesene
161. pentyl.octanoate
162. X.E..beta.farnesene
163. X2.methylbutyl.octanoate
164. alpha.humulene
165. neryl.propanoate
166. X9.epi..E..caryophyllene
167. ethyl..E..cinnamate
168. linalool.isovalerate
169. alpha.terpinyl.isobutanoate
170. n.dodecanol
171. germacrene.D
172. X.E..beta.ionone
173. valencene
174. neryl.isobutanoate
175. E.methyl.isoeugenol
176. X.Z..dihydro.apofarnesal
177. butylated.hydroxytoluene
178. X.E..dihydro.apofarnesal
179. Z.nerolidol
180. X.E..ortho.methoxy.cinnamaldehyde
181. alpha.calacorene
182. E.nerolidol
183. dihydroisocaryophyllene.epoxide
184. caryophyllene.alcohol
185. neryl.isovalerate
186. spathulenol
187. caryophyllene.oxide
188. humulene.epoxide.II
189. alloaromadendrene.epoxide
190. X1.10.di.epi.cubenol
191. isopropyl.laurate
192. caryophylla.4.12..8.13..dien.5.alpha.ol
193. gamma.eudesmol
194. alpha.muurolol
195. X1.2.dihydro.8.hydroxy..2E..linalool
196. tau.cadinol
197. selin.11.en.4.alpha.ol
198. alpha.eudesmol
199. X14.hydroxy.9.epi..E..caryophyllene
200. tau.muurolol
201. n.tetradecanol
202. foeniculin
203. cadalene
204. X2.3.dihydro.farnesol
205. X2E.6Z.farnesal
206. caryophyllene.acetate
207. X14.hydroxy.alpha.humulene
208. X2Z.6E.farnesal
209. X2Z.6Z.farnesol
210. X2Z.6E.farnesol
211. ambroxide
212. benzyl.benzoate
213. X2E.6E.methyl.farnesoate
214. ethyl.tetradecanoate
215. X2.ethylhexylsalicylate
216. isopropyl.tetradecanoate
217. ethyl.pentadecanoate
218. methyl.hexadecanoate
219. Z.Z.geranyl.linalool
220. ethyl.hexadecanoate
221. manool.oxide
222. X13.epi.manool.oxide
223. isopropyl.hexadecanoate
224. manool
225. ethyl.octadecanoate
226. ethyl.pentanoate
227. X2.ethyl.3.methylpyrazine
228. esters_sum
229. aroma_hops_sum
230. acids_sum
231. sulfur_sum

In [48]:
# 读取评分卡，提取文字，查看感官维度和评分说明
card = pd.read_excel(
    data_dir / "3.xlsx",
    sheet_name="beer_1",
    header=None
)

for row_num, row in card.iterrows():
    texts = [
        f"{col_num + 1}列：{value.strip()}"
        for col_num, value in row.items()
        if isinstance(value, str) and value.strip()
    ]

    if texts:
        print(f"第{row_num + 1}行 | " + " | ".join(texts))

第1行 | 2列：Date
第3行 | 2列：Name: | 18列：Beer#:
第5行 | 2列：Aroma | 18列：Flavour
第6行 | 2列：Malt | 18列：Malt
第10行 | 5列：Cereals, flour, grains | 21列：Cereals, flour, grains
第12行 | 5列：Bread crust | 21列：Bread crust
第14行 | 5列：Caramel | 21列：Caramel
第16行 | 5列：Smoked, burnt toast | 21列：Smoked, burnt toast
第19行 | 2列：Hops | 18列：Hops
第23行 | 5列：Citrus | 21列：Citrus
第25行 | 5列：Tropical fruit | 21列：Tropical fruit
第27行 | 5列：Noble hops (dried herbs, dried grass, hay) | 21列：Noble hops (dried herbs, dried grass, hay)
第29行 | 5列：Pine, woody, resinous | 21列：Pine, woody, resinous
第32行 | 2列：Esters | 18列：Esters
第36行 | 5列：Ethyl acetate, solvent, nail polish | 21列：Ethyl acetate, solvent, nail polish
第38行 | 5列：Banana, pear, candy | 21列：Banana, pear, candy
第40行 | 5列：Flowers, roses | 21列：Flowers, roses
第42行 | 5列：Sweet, fruity, apples | 21列：Sweet, fruity, apples
第44行 | 2列：Acetaldehyde (green apples, peel) | 18列：Acetaldehyde (green apples, peel)
第49行 | 2列：Body | 18列：Alcohol
第53行 | 2列：Bitterness | 18列：Sweetness
第57行 | 2列：Carbonation | 18列：Acidity/sourness
第61行 | 2列：Aftertaste
第66行 | 2列：Faults
第67行 | 2列：DMS (cooked cabbage, corn) | 18列：Trans-2-nonenal (wet cardboard, old attic, papery)
第71行 | 2列：Metallic | 18列：Diacetyl (buttery, caramel/butterscotch)
第75行 | 2列：4VG (smoky, clove, medicinal, dentist) | 18列：Stale hops (cheesy, roquefort)
第80行 | 2列：Spiced beers | 18列：Lambic/Geuze
第81行 | 2列：Orange | 18列：Lactic acid
第85行 | 2列：Coriander | 18列：Acetic acid
第89行 | 2列：Clove/anise | 18列：Barnyard/horsey
第93行 | 2列：Overall | 18列：Comments:
第97行 | 5列：Not present
第100行 | 5列：Predominant/overwhelming

In [49]:
# 全部感官标签，排除样本信息
score_cols = sensory.columns.drop(
    ["beer", "beer_id", "tasting_category_fine"]
)

# 当前已预测的30项
predicted_cols = [
    col for col in score_cols
    if col.startswith(("A_", "F_"))
]

# 其余标签
other_cols = [
    col for col in score_cols
    if col not in predicted_cols
]

print("全部感官标签数：", len(score_cols))
print("当前已预测数量：", len(predicted_cols))

print("\n其余感官标签：")
for i, col in enumerate(other_cols, 1):
    print(f"{i:2d}. {col}")

print("\n名称中包含乙醛 acetaldehyde 的感官标签：")
print([
    col for col in score_cols
    if "acetaldehyde" in col.lower()
])

全部感官标签数： 50
当前已预测数量： 30

其余感官标签：
 1. acidity
 2. bitternes
 3. sweetness
 4. X4vg
 5. diacetyl
 6. dms
 7. metallic
 8. stale_hops
 9. t2n
10. orange
11. coriander
12. clove
13. lactic
14. acetic
15. barnyard
16. alcohol
17. aftertaste
18. body
19. co2
20. overall

名称中包含乙醛 acetaldehyde 的感官标签：
[]

In [50]:
summary_card = pd.read_excel(
    data_dir / "3.xlsx",
    sheet_name="summary",
    header=None
)

# 删除全空行、全空列，只影响展示
summary_card = (
    summary_card
    .dropna(how="all")
    .dropna(axis=1, how="all")
)

print("非空区域大小：", summary_card.shape)
print(summary_card.to_string(index=False, header=False))

非空区域大小： (13, 52)
Beer A_malt_all A_malt_grain A_malt_bread A_malt_cara A_malt_burn A_hops_all A_hops_citrus A_hops_tropical A_hops_noble A_hops_woody A_esters_all A_esters_ethac A_esters_isoaa A_esters_flower A_ester_fruity F_malt_all F_malt_grain F_malt_bread F_malt_cara F_malt_burn F_hops_all F_hops_citrus F_hops_tropical F_hops_noble F_hops_woody F_esters_all F_esters_ethac F_esters_isoaa F_esters_flower F_ester_fruity body bitternes co2 aftertaste alcohol sweetness acidity dms metallic 4vg t2n diacetyl stale_hops orange coriander clove lactic acetic barnyard overall comments
   1          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
   2          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
   3          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
   4          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
   5          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
   6          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
   7          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
   8          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
   9          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
  10          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
  11          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0
  12          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0          0            0            0           0           0          0             0               0            0            0            0              0              0               0              0    0         0   0          0       0         0       0   0        0   0   0        0          0      0         0     0      0      0        0       0        0

In [51]:
book8 = pd.ExcelFile(data_dir / "8.xlsx")

for sheet_name in book8.sheet_names:
    table = pd.read_excel(book8, sheet_name=sheet_name)

    # 去除全空行、列
    table = table.dropna(how="all").dropna(axis=1, how="all")

    print(f"\n===== {sheet_name} =====")
    print("大小：", table.shape)
    print("全部列名：", table.columns.tolist())
    print("前两行（最多展示前8列）：")
    print(table.iloc[:2, :8].to_string(index=False))

===== Sensory thresholds =====
大小： (261, 11)
全部列名： ['field_name_python', 'field_name_R', 'chemical_name', 'chemical_name_short', 'calibrated', 'origin_paper', 'unit', 'aging', 'off_flavors', 'threshold_mean', 'threshold_median']
前两行（最多展示前8列）：
field_name_python     field_name_R   chemical_name chemical_name_short calibrated               origin_paper unit aging
  2,3-hexanedione X2.3.hexanedione 2,3-hexanedione     2,3-hexanedione        NaN Internal standard solution  NaN   NaN
 acetic acid.g.L. acetic_acid.g.L.     Acetic acid         Acetic acid        yes                 Wild flora  g/L   NaN

===== Sensory names =====
大小： (101, 8)
全部列名： ['dataset', 'R_name', 'Category_Paper', 'Category', 'CleanName_Paper', 'CleanName_PaperLong', 'CleanName_PanelFeedback', 'DataType']
前两行（最多展示前8列）：
      dataset         R_name Category_Paper Category      CleanName_Paper        CleanName_PaperLong    CleanName_PanelFeedback    DataType
Trained panel   A_esters_all          Aroma    Yeast     Esters - overall               Esters aroma     Esters aroma - overall     numeric
Trained panel A_esters_ethac          Aroma    Yeast Esters - nail polish Esters aroma - nail polish Esters aroma - nail polish categorical

===== GBM importance MDI =====
大小： (231, 2)
全部列名： ['Unnamed: 0', 0]
前两行（最多展示前8列）：
 Unnamed: 0            0
   0.008620 acetaldehyde
   0.000342          CS2

===== GBM SHAP Values =====
大小： (500, 236)
全部列名： ['data', 'beer', 'beer_id', 'tasting_category_fine', 'acetaldehyde', 'CS2', 'DES', 'DMS', 'ethyl_2.methyl_butyrate', 'ethyl_acetate', 'ethyl_decanoate', 'ethyl_hexanoate', 'ethyl_isovalerate', 'ethyl_octanoate', 'ethyl_propionate', 'H2S', 'isoamyl_alcohol', 'isobutanol', 'isobutyl_acetate', 'isopentyl_acetate', 'MeSH', 'octyl_acetate', 'phenethyl_acetate', 'phenethyl_alcohol', 'X4VG', 'SO2.mg.L.', 'acetic_acid.g.L.', 'ammonia.mg.L.', 'color.EBC.', 'betaglucan.mg.L.', 'lactic_acid.mg.L.', 'glycerol', 'iron', 'pH', 'protein.g.L.', 'bitterness', 'GFS', 'ethanol..v.v.', 'CO2.PSI.', 'unfermentables', 'kcalperc', 'X1.propanol', 'X2.3.butanedione', 'X3.methylbutanal', 'propylene.glycol', 'propyl.acetate', 'n.pentanol', 'X2.methyl.1.butanol', 'isopentyl.formate', 'ethyl.isobutyrate', 'X3.methyl.2.butenal', 'X2.methyltetrahydrofuran.3.one', 'ethyl.butyrate', 'butyl.acetate', 'methylpyrazine', 'furfural', 'ethyl.lactate', 'X3Z.hexenol', 'n.hexanol', 'styrene', 'X2.furanmethanol', 'X3.methyl.2.hexanol', 'X3.furanmethanol', 'X2.acetylfuran', 'X2.6.dimethyl.pyrazine', 'amyl.acetate', 'ethyl.tiglate', 'benzaldehyde', 'X5.methylfurfural', 'n.heptanol', 'X1.octen.3.ol', 'X3.methylthio.propanol', 'isomaltol', 'X6.methyl.5.hepten.2.one', 'X2.pentyl.furan', 'ethyl.hex..3E..enoate', 'alpha.phellandrene', 'dehydroxy.cis.linalool.oxide', 'hexyl.acetate', 'isopentyl.butanoate', 'X2.ethyl.1.hexanol', 'beta.phellandrene', 'limonene', 'eucalyptol', 'benzyl.alcohol', 'ethyl.hex..2E..enoate', 'phenylacetaldehyde', 'X.E..beta.ocimene', 'prenyl.isobutyrate', 'ethyl.furoate', 'ortho.cresol', 'ethyl.5.methylhexanoate', 'X2.acetylpyrrole', 'isoamyl.lactate', 'n.octanol', 'cis.linalool.oxide', 'meta.cymenene', 'terpinolene', 'linalool', 'nonan.2.ol', 'n.nonanal', 'X2.methyl.benzofuran', 'heptyl.acetate', 'X4.methyl.1.pentanol', 'neo.allo.ocimene', 'x.methyl.1.octanol', 'trans.dihydro.beta.terpineol', 'cis.beta.terpineol', 'y.methyl.1.octanol', 'camphor', 'isobutyl.hexanoate', 'nerol.oxide', 'X.E..2.nonenal', 'cis.dihydro.beta.terpineol', 'X4.ethyl.phenol', 'isoborneol', 'ethyl.benzoate', 'n.nonanol', 'terpinen.4.ol', 'diethyl.succinate', 'vinyl.caprylate', 'X1.alpha.terpineol', 'ethyl..E..linalool', 'ethyl.nicotinate', 'citronellol', 'nerol', 'hydroxy.methyl.furfural', 'E.ocimenone', 'cumin.aldehyde', 'ethyl.phenylacetate', 'isopentyl.hexanoate', 'geraniol', 'beta.cyclohomocitral', 'E.cinnamaldehyde', 'n.decanol', 'neryl.formate', 'X4.ethyl.guaiacol', 'X2.undecanone', 'trans.dihydro.alpha.terpinyl.acetate', 'terpinen.4.ol.acetate', 'X2.undecanol', 'delta.terpinyl.acetate', 'X.E.E..2.4.decadienal', 'methyl.geranate', 'car.3.en.2.one', 'dimethoxy..E..citral', 'X2.butyloctanoate', 'X4.methoxysalicylaldehyde', 'ethyl.hydrocinnamate', 'eugenol', 'gamma.nonalactone', 'methyl.para.anisate', 'X.E..beta.damascenone', 'ethyl..9..decenoate', 'vanillin', 'geosmin', 'dodecanal', 'X4.8.alpha.epoxy.caryophyllane', 'E.caryophyllene', 'X.E..alpha.ionone', 'perillyl.acetate', 'beta.humulene', 'X2.phenyl.ethyl.butyrate', 'X.Z..beta.farnesene', 'pentyl.octanoate', 'X.E..beta.farnesene', 'X2.methylbutyl.octanoate', 'alpha.humulene', 'neryl.propanoate', 'X9.epi..E..caryophyllene', 'ethyl..E..cinnamate', 'linalool.isovalerate', 'alpha.terpinyl.isobutanoate', 'n.dodecanol', 'germacrene.D', 'X.E..beta.ionone', 'valencene', 'neryl.isobutanoate', 'E.methyl.isoeugenol', 'X.Z..dihydro.apofarnesal', 'butylated.hydroxytoluene', 'X.E..dihydro.apofarnesal', 'Z.nerolidol', 'X.E..ortho.methoxy.cinnamaldehyde', 'alpha.calacorene', 'E.nerolidol', 'dihydroisocaryophyllene.epoxide', 'caryophyllene.alcohol', 'neryl.isovalerate', 'spathulenol', 'caryophyllene.oxide', 'humulene.epoxide.II', 'alloaromadendrene.epoxide', 'X1.10.di.epi.cubenol', 'isopropyl.laurate', 'caryophylla.4.12..8.13..dien.5.alpha.ol', 'gamma.eudesmol', 'alpha.muurolol', 'X1.2.dihydro.8.hydroxy..2E..linalool', 'tau.cadinol', 'selin.11.en.4.alpha.ol', 'alpha.eudesmol', 'X14.hydroxy.9.epi..E..caryophyllene', 'tau.muurolol', 'n.tetradecanol', 'foeniculin', 'cadalene', 'X2.3.dihydro.farnesol', 'X2E.6Z.farnesal', 'caryophyllene.acetate', 'X14.hydroxy.alpha.humulene', 'X2Z.6E.farnesal', 'X2Z.6Z.farnesol', 'X2Z.6E.farnesol', 'ambroxide', 'benzyl.benzoate', 'X2E.6E.methyl.farnesoate', 'ethyl.tetradecanoate', 'X2.ethylhexylsalicylate', 'isopropyl.tetradecanoate', 'ethyl.pentadecanoate', 'methyl.hexadecanoate', 'Z.Z.geranyl.linalool', 'ethyl.hexadecanoate', 'manool.oxide', 'X13.epi.manool.oxide', 'isopropyl.hexadecanoate', 'manool', 'ethyl.octadecanoate', 'ethyl.pentanoate', 'X2.ethyl.3.methylpyrazine', 'esters_sum', 'aroma_hops_sum', 'acids_sum', 'sulfur_sum', 'base_prediction']
前两行（最多展示前8列）：
data  beer       beer_id tasting_category_fine  acetaldehyde       CS2       DES       DMS
SHAP    10 5410228202929        Low/No alcohol     -0.002579 -0.000811 -0.009588 -0.004363
SHAP    86 5410783031019        Low/No alcohol     -0.002491 -0.000628  0.006789 -0.007325

===== Calibrated chemical dataset =====
大小： (250, 73)
全部列名： ['beer', 'beer_id', 'tasting_category_fine', 'acetaldehyde', 'CS2', 'DES', 'DMS', 'ethyl_2.methyl_butyrate', 'ethyl_acetate', 'ethyl_decanoate', 'ethyl_hexanoate', 'ethyl_isovalerate', 'ethyl_octanoate', 'ethyl_propionate', 'H2S', 'isoamyl_alcohol', 'isobutanol', 'isobutyl_acetate', 'isopentyl_acetate', 'MeSH', 'octyl_acetate', 'phenethyl_acetate', 'phenethyl_alcohol', 'X4VG', 'SO2.mg.L.', 'acetic_acid.g.L.', 'ammonia.mg.L.', 'color.EBC.', 'betaglucan.mg.L.', 'lactic_acid.mg.L.', 'glycerol', 'iron', 'pH', 'protein.g.L.', 'bitterness', 'GFS', 'ethanol..v.v.', 'CO2.PSI.', 'unfermentables', 'kcalperc', 'X2.3.butanedione', 'X3.methylbutanal', 'ethyl.isobutyrate', 'ethyl.butyrate', 'X2.methyltetrahydrofuran.3.one', 'methylpyrazine', 'furfural', 'X3Z.hexenol', 'n.hexanol', 'styrene', 'ethyl.pentanoate', 'amyl.acetate', 'benzaldehyde', 'X5.methylfurfural', 'X2.ethyl.3.methylpyrazine', 'hexyl.acetate', 'benzyl.alcohol', 'phenylacetaldehyde', 'X.E..beta.ocimene', 'linalool', 'X.E..2.nonenal', 'diethyl.succinate', 'X1.alpha.terpineol', 'ethyl.nicotinate', 'citronellol', 'geraniol', 'X.E.E..2.4.decadienal', 'eugenol', 'gamma.nonalactone', 'X.E..beta.damascenone', 'E.caryophyllene', 'alpha.humulene', 'Z.nerolidol']
前两行（最多展示前8列）：
 beer       beer_id tasting_category_fine  acetaldehyde  CS2      DES      DMS  ethyl_2.methyl_butyrate
   10 5410228202929        Low/No alcohol      0.228170  0.0 0.000000 0.000000                      0.0
   86 5410783031019        Low/No alcohol      0.668615  0.0 0.553225 2.224545                      0.0

===== Beer Prices =====
大小： (250, 11)
全部列名： ['beer', 'beer_id', 'tasting_category', 'ABV', 'Price_TotalWine_USA', 'Price_Colruyt_Belgium', 'Price_Delhaize_Belgium', 'Price_BeerHawk_UK', 'Price_TheBelgianBeerShop_global', 'Price_TheBelgianShop_global', 'Price_BeerOfBelgium_global']
前两行（最多展示前8列）：
 beer       beer_id tasting_category  ABV  Price_TotalWine_USA  Price_Colruyt_Belgium  Price_Delhaize_Belgium  Price_BeerHawk_UK
    1 5413970150111             brut  9.0                  NaN                    NaN                     NaN                NaN
    2 5410228142003   low_no alcohol  0.5                  NaN                    NaN                    2.63               5.81

===== Sheet2 =====
大小： (0, 0)
全部列名： []
前两行（最多展示前8列）：
Empty DataFrame
Columns: []
Index: []

In [52]:
extra_sensory = pd.read_csv(data_dir / "7.csv")

print("附件7大小：", extra_sensory.shape)

print("\n全部列名：")
print(extra_sensory.columns.tolist())

# 与附件4比较字段名
extra_cols = [
    col for col in extra_sensory.columns
    if col not in sensory.columns
]

print("\n附件7比附件4多出的字段：")
print(extra_cols)

print("\n前3行、前8列：")
print(extra_sensory.iloc[:3, :8].to_string(index=False))

附件7大小： (250, 189)

全部列名：
['beer', 'beer_id', 'tasting_category_fine', 'aroma_acetaldehyde', 'aroma_acetate', 'aroma_acetic', 'aroma_acidic', 'aroma_aftertaste', 'aroma_alcohol', 'aroma_anise', 'aroma_apple', 'aroma_banana', 'aroma_barnyard', 'aroma_bitter', 'aroma_blanket', 'aroma_bread', 'aroma_burnt', 'aroma_butterscotch', 'aroma_buttery', 'aroma_cabbage', 'aroma_candy', 'aroma_caramel', 'aroma_carbonation', 'aroma_cardboard', 'aroma_cereal', 'aroma_cheesy', 'aroma_citrus', 'aroma_clove', 'aroma_coriander', 'aroma_corn', 'aroma_dentist', 'aroma_diacetyl', 'aroma_estery', 'aroma_flour', 'aroma_flower', 'aroma_fruity', 'aroma_grainy', 'aroma_grape', 'aroma_grass', 'aroma_hay', 'aroma_herb', 'aroma_hoppy', 'aroma_horse', 'aroma_kiwi', 'aroma_lactic', 'aroma_lychee', 'aroma_malt', 'aroma_mango', 'aroma_medicinal', 'aroma_metallic', 'aroma_orange', 'aroma_papaya', 'aroma_papery', 'aroma_pear', 'aroma_pine', 'aroma_pineapple', 'aroma_resinous', 'aroma_smoky', 'aroma_solvent', 'aroma_sour', 'aroma_stale', 'aroma_sweet', 'aroma_toast', 'aroma_tropical', 'aroma_woody', 'palate_acetaldehyde', 'palate_acetate', 'palate_acetic', 'palate_acidic', 'palate_aftertaste', 'palate_alcohol', 'palate_anise', 'palate_apple', 'palate_banana', 'palate_barnyard', 'palate_bitter', 'palate_blanket', 'palate_bread', 'palate_burnt', 'palate_butterscotch', 'palate_buttery', 'palate_cabbage', 'palate_candy', 'palate_caramel', 'palate_carbonation', 'palate_cardboard', 'palate_cereal', 'palate_cheesy', 'palate_citrus', 'palate_clove', 'palate_coriander', 'palate_corn', 'palate_dentist', 'palate_diacetyl', 'palate_estery', 'palate_flour', 'palate_flower', 'palate_fruity', 'palate_grainy', 'palate_grape', 'palate_grass', 'palate_hay', 'palate_herb', 'palate_hoppy', 'palate_horse', 'palate_kiwi', 'palate_lactic', 'palate_lychee', 'palate_malt', 'palate_mango', 'palate_medicinal', 'palate_metallic', 'palate_orange', 'palate_papaya', 'palate_papery', 'palate_pear', 'palate_pine', 'palate_pineapple', 'palate_resinous', 'palate_smoky', 'palate_solvent', 'palate_sour', 'palate_stale', 'palate_sweet', 'palate_toast', 'palate_tropical', 'palate_woody', 'taste_acetaldehyde', 'taste_acetate', 'taste_acetic', 'taste_acidic', 'taste_aftertaste', 'taste_alcohol', 'taste_anise', 'taste_apple', 'taste_banana', 'taste_barnyard', 'taste_bitter', 'taste_blanket', 'taste_bread', 'taste_burnt', 'taste_butterscotch', 'taste_buttery', 'taste_cabbage', 'taste_candy', 'taste_caramel', 'taste_carbonation', 'taste_cardboard', 'taste_cereal', 'taste_cheesy', 'taste_citrus', 'taste_clove', 'taste_coriander', 'taste_corn', 'taste_dentist', 'taste_diacetyl', 'taste_estery', 'taste_flour', 'taste_flower', 'taste_fruity', 'taste_grainy', 'taste_grape', 'taste_grass', 'taste_hay', 'taste_herb', 'taste_hoppy', 'taste_horse', 'taste_kiwi', 'taste_lactic', 'taste_lychee', 'taste_malt', 'taste_mango', 'taste_medicinal', 'taste_metallic', 'taste_orange', 'taste_papaya', 'taste_papery', 'taste_pear', 'taste_pine', 'taste_pineapple', 'taste_resinous', 'taste_smoky', 'taste_solvent', 'taste_sour', 'taste_stale', 'taste_sweet', 'taste_toast', 'taste_tropical', 'taste_woody']

附件7比附件4多出的字段：
['aroma_acetaldehyde', 'aroma_acetate', 'aroma_acetic', 'aroma_acidic', 'aroma_aftertaste', 'aroma_alcohol', 'aroma_anise', 'aroma_apple', 'aroma_banana', 'aroma_barnyard', 'aroma_bitter', 'aroma_blanket', 'aroma_bread', 'aroma_burnt', 'aroma_butterscotch', 'aroma_buttery', 'aroma_cabbage', 'aroma_candy', 'aroma_caramel', 'aroma_carbonation', 'aroma_cardboard', 'aroma_cereal', 'aroma_cheesy', 'aroma_citrus', 'aroma_clove', 'aroma_coriander', 'aroma_corn', 'aroma_dentist', 'aroma_diacetyl', 'aroma_estery', 'aroma_flour', 'aroma_flower', 'aroma_fruity', 'aroma_grainy', 'aroma_grape', 'aroma_grass', 'aroma_hay', 'aroma_herb', 'aroma_hoppy', 'aroma_horse', 'aroma_kiwi', 'aroma_lactic', 'aroma_lychee', 'aroma_malt', 'aroma_mango', 'aroma_medicinal', 'aroma_metallic', 'aroma_orange', 'aroma_papaya', 'aroma_papery', 'aroma_pear', 'aroma_pine', 'aroma_pineapple', 'aroma_resinous', 'aroma_smoky', 'aroma_solvent', 'aroma_sour', 'aroma_stale', 'aroma_sweet', 'aroma_toast', 'aroma_tropical', 'aroma_woody', 'palate_acetaldehyde', 'palate_acetate', 'palate_acetic', 'palate_acidic', 'palate_aftertaste', 'palate_alcohol', 'palate_anise', 'palate_apple', 'palate_banana', 'palate_barnyard', 'palate_bitter', 'palate_blanket', 'palate_bread', 'palate_burnt', 'palate_butterscotch', 'palate_buttery', 'palate_cabbage', 'palate_candy', 'palate_caramel', 'palate_carbonation', 'palate_cardboard', 'palate_cereal', 'palate_cheesy', 'palate_citrus', 'palate_clove', 'palate_coriander', 'palate_corn', 'palate_dentist', 'palate_diacetyl', 'palate_estery', 'palate_flour', 'palate_flower', 'palate_fruity', 'palate_grainy', 'palate_grape', 'palate_grass', 'palate_hay', 'palate_herb', 'palate_hoppy', 'palate_horse', 'palate_kiwi', 'palate_lactic', 'palate_lychee', 'palate_malt', 'palate_mango', 'palate_medicinal', 'palate_metallic', 'palate_orange', 'palate_papaya', 'palate_papery', 'palate_pear', 'palate_pine', 'palate_pineapple', 'palate_resinous', 'palate_smoky', 'palate_solvent', 'palate_sour', 'palate_stale', 'palate_sweet', 'palate_toast', 'palate_tropical', 'palate_woody', 'taste_acetaldehyde', 'taste_acetate', 'taste_acetic', 'taste_acidic', 'taste_aftertaste', 'taste_alcohol', 'taste_anise', 'taste_apple', 'taste_banana', 'taste_barnyard', 'taste_bitter', 'taste_blanket', 'taste_bread', 'taste_burnt', 'taste_butterscotch', 'taste_buttery', 'taste_cabbage', 'taste_candy', 'taste_caramel', 'taste_carbonation', 'taste_cardboard', 'taste_cereal', 'taste_cheesy', 'taste_citrus', 'taste_clove', 'taste_coriander', 'taste_corn', 'taste_dentist', 'taste_diacetyl', 'taste_estery', 'taste_flour', 'taste_flower', 'taste_fruity', 'taste_grainy', 'taste_grape', 'taste_grass', 'taste_hay', 'taste_herb', 'taste_hoppy', 'taste_horse', 'taste_kiwi', 'taste_lactic', 'taste_lychee', 'taste_malt', 'taste_mango', 'taste_medicinal', 'taste_metallic', 'taste_orange', 'taste_papaya', 'taste_papery', 'taste_pear', 'taste_pine', 'taste_pineapple', 'taste_resinous', 'taste_smoky', 'taste_solvent', 'taste_sour', 'taste_stale', 'taste_sweet', 'taste_toast', 'taste_tropical', 'taste_woody']

前3行、前8列：
 beer      beer_id tasting_category_fine  aroma_acetaldehyde  aroma_acetate  aroma_acetic  aroma_acidic  aroma_aftertaste
   10 5.410230e+12        Low/No alcohol           -0.145066      -0.139059     -0.308488     -0.541218         -0.412412
   86 5.410780e+12        Low/No alcohol           -0.145066      -0.139059     -0.308488     -0.541218         -0.412412
    2 5.410230e+12        Low/No alcohol           -0.145066      -0.139059     -0.308488     -0.541218         -0.412412

In [53]:
# 读取评分卡汇总表的表头
card_summary = pd.read_excel(
    data_dir / "3.xlsx",
    sheet_name="summary"
)

# 评分卡与附件4之间的拼写差异
name_fixes = {
    "A_ester_fruity": "A_esters_fruity",
    "F_ester_fruity": "F_esters_fruity",
    "4vg": "X4vg"
}

mapping_rows = []

for col in card_summary.columns:
    name = str(col).strip()

    if name.lower() in ["beer", "comments"]:
        continue
    if name.startswith("Unnamed:"):
        continue

    target = name_fixes.get(name, name)

    mapping_rows.append({
        "评分卡字段": name,
        "附件4字段": target,
        "是否匹配": target in score_cols
    })

score_mapping = pd.DataFrame(mapping_rows)

print(score_mapping.to_string(index=False))
print("\n评分卡维度数：", len(score_mapping))
print("成功匹配数：", score_mapping["是否匹配"].sum())
print("映射后是否存在重复：",
      score_mapping["附件4字段"].duplicated().any())

print("\n附件4中未被评分卡覆盖的标签：")
print([
    col for col in score_cols
    if col not in score_mapping["附件4字段"].tolist()
])

          评分卡字段           附件4字段  是否匹配
     A_malt_all      A_malt_all  True
   A_malt_grain    A_malt_grain  True
   A_malt_bread    A_malt_bread  True
    A_malt_cara     A_malt_cara  True
    A_malt_burn     A_malt_burn  True
     A_hops_all      A_hops_all  True
  A_hops_citrus   A_hops_citrus  True
A_hops_tropical A_hops_tropical  True
   A_hops_noble    A_hops_noble  True
   A_hops_woody    A_hops_woody  True
   A_esters_all    A_esters_all  True
 A_esters_ethac  A_esters_ethac  True
 A_esters_isoaa  A_esters_isoaa  True
A_esters_flower A_esters_flower  True
 A_ester_fruity A_esters_fruity  True
     F_malt_all      F_malt_all  True
   F_malt_grain    F_malt_grain  True
   F_malt_bread    F_malt_bread  True
    F_malt_cara     F_malt_cara  True
    F_malt_burn     F_malt_burn  True
     F_hops_all      F_hops_all  True
  F_hops_citrus   F_hops_citrus  True
F_hops_tropical F_hops_tropical  True
   F_hops_noble    F_hops_noble  True
   F_hops_woody    F_hops_woody  True
   F_esters_all    F_esters_all  True
 F_esters_ethac  F_esters_ethac  True
 F_esters_isoaa  F_esters_isoaa  True
F_esters_flower F_esters_flower  True
 F_ester_fruity F_esters_fruity  True
           body            body  True
      bitternes       bitternes  True
            co2             co2  True
     aftertaste      aftertaste  True
        alcohol         alcohol  True
      sweetness       sweetness  True
        acidity         acidity  True
            dms             dms  True
       metallic        metallic  True
            4vg            X4vg  True
            t2n             t2n  True
       diacetyl        diacetyl  True
     stale_hops      stale_hops  True
         orange          orange  True
      coriander       coriander  True
          clove           clove  True
         lactic          lactic  True
         acetic          acetic  True
       barnyard        barnyard  True
        overall         overall  True

评分卡维度数： 50
成功匹配数： 50
映射后是否存在重复： False

附件4中未被评分卡覆盖的标签：
[]

In [54]:
from sklearn.model_selection import cross_val_score

# 找出原模型比较表中尚未覆盖的评分项
existing_targets = set(selection["指标"])

extra_targets = [
    col for col in score_mapping["附件4字段"]
    if col not in existing_targets
]

# 按训练集啤酒编号对齐，避免行顺序错位
extra_Y_train = Y.loc[X_train.index, extra_targets]

assert X_train.index.equals(extra_Y_train.index)
assert not extra_Y_train.isna().any().any()

print("本次新增目标数量：", len(extra_targets))

# 沿用原来的三个候选模型
extra_models = {
    "基准MAE": model_templates["均值基准"],
    "岭回归MAE": model_templates["岭回归"],
    "森林MAE": model_templates["随机森林"]
}

extra_rows = []

for i, target in enumerate(extra_targets, 1):
    row = {"指标": target}

    for score_name, estimator in extra_models.items():
        row[score_name] = -cross_val_score(
            estimator,
            X_train,
            extra_Y_train[target],
            cv=cv,
            scoring="neg_mean_absolute_error"
        ).mean()

    extra_rows.append(row)
    print(f"已完成 {i}/{len(extra_targets)}：{target}")

extra_selection = pd.DataFrame(extra_rows)

score_names = ["基准MAE", "岭回归MAE", "森林MAE"]

extra_selection["候选模型"] = (
    extra_selection[score_names]
    .idxmin(axis=1)
    .map({
        "基准MAE": "均值基准",
        "岭回归MAE": "岭回归",
        "森林MAE": "随机森林"
    })
)

extra_selection["CV改善率%"] = (
    1
    - extra_selection[score_names].min(axis=1)
    / extra_selection["基准MAE"]
) * 100

print("\n新增20项的交叉验证结果：")
print(extra_selection.round(3).to_string(index=False))

本次新增目标数量： 20
已完成 1/20：body
已完成 2/20：bitternes
已完成 3/20：co2
已完成 4/20：aftertaste
已完成 5/20：alcohol
已完成 6/20：sweetness
已完成 7/20：acidity
已完成 8/20：dms
已完成 9/20：metallic
已完成 10/20：X4vg
已完成 11/20：t2n
已完成 12/20：diacetyl
已完成 13/20：stale_hops
已完成 14/20：orange
已完成 15/20：coriander
已完成 16/20：clove
已完成 17/20：lactic
已完成 18/20：acetic
已完成 19/20：barnyard
已完成 20/20：overall

新增20项的交叉验证结果：
        指标  基准MAE  岭回归MAE  森林MAE 候选模型  CV改善率%
      body  0.438   0.306  0.297 随机森林  32.332
 bitternes  0.571   0.368  0.339 随机森林  40.683
       co2  0.464   0.426  0.364 随机森林  21.463
aftertaste  0.475   0.350  0.333 随机森林  29.888
   alcohol  0.597   0.350  0.343 随机森林  42.562
 sweetness  0.510   0.458  0.403 随机森林  20.987
   acidity  0.592   0.374  0.296 随机森林  49.964
       dms  0.391   0.411  0.381 随机森林   2.469
  metallic  0.385   0.392  0.372 随机森林   3.294
      X4vg  0.438   0.414  0.353 随机森林  19.589
       t2n  0.308   0.325  0.303 随机森林   1.543
  diacetyl  0.397   0.423  0.393 随机森林   0.980
stale_hops  0.312   0.324  0.313 均值基准   0.000
    orange  0.362   0.399  0.314 随机森林  13.285
 coriander  0.277   0.277  0.238 随机森林  14.147
     clove  0.285   0.330  0.268 随机森林   5.869
    lactic  0.508   0.290  0.202 随机森林  60.284
    acetic  0.480   0.324  0.170 随机森林  64.596
  barnyard  0.315   0.333  0.319 均值基准   0.000
   overall  0.419   0.413  0.392 随机森林   6.523

In [55]:
extra_test_rows = []
extra_prediction_frames = []

for _, row in extra_selection.iterrows():
    target = row["指标"]
    model_name = row["候选模型"]

    train_y = Y.loc[X_train.index, target]
    actual = Y.loc[X_test.index, target]

    # 按交叉验证选定的模型训练，不根据测试结果换模型
    estimator = clone(model_templates[model_name])
    estimator.fit(X_train, train_y)
    pred = estimator.predict(X_test)

    # 使用训练集均值作为比较基准
    base_pred = np.full(len(actual), train_y.mean())

    base_mae = mean_absolute_error(actual, base_pred)
    model_mae = mean_absolute_error(actual, pred)

    extra_test_rows.append({
        "指标": target,
        "模型": model_name,
        "测试基准MAE": base_mae,
        "测试MAE": model_mae,
        "测试RMSE": mean_squared_error(actual, pred) ** 0.5,
        "测试R²": r2_score(actual, pred),
        "测试改善率%": (
            (1 - model_mae / base_mae) * 100
            if base_mae > 0 else np.nan
        )
    })

    extra_prediction_frames.append(pd.DataFrame({
        "beer": X_test.index,
        "指标": target,
        "模型": model_name,
        "真实值": actual.to_numpy(),
        "预测值": pred,
        "基准预测值": base_pred
    }))

extra_test_results = pd.DataFrame(extra_test_rows)
extra_test_predictions = pd.concat(
    extra_prediction_frames, ignore_index=True
)

print(extra_test_results.round(3).to_string(index=False))

print(
    "\n测试MAE优于基准的指标数：",
    (extra_test_results["测试改善率%"] > 0).sum(),
    "/", len(extra_test_results)
)

        指标   模型  测试基准MAE  测试MAE  测试RMSE   测试R²  测试改善率%
      body 随机森林    0.527  0.382   0.463  0.479  27.655
 bitternes 随机森林    0.607  0.379   0.484  0.611  37.565
       co2 随机森林    0.576  0.460   0.548  0.370  20.134
aftertaste 随机森林    0.482  0.391   0.501  0.432  18.796
   alcohol 随机森林    0.577  0.310   0.377  0.738  46.290
 sweetness 随机森林    0.510  0.414   0.555  0.447  18.742
   acidity 随机森林    0.580  0.280   0.436  0.697  51.763
       dms 随机森林    0.336  0.309   0.385  0.130   8.028
  metallic 随机森林    0.400  0.403   0.480 -0.062  -0.875
      X4vg 随机森林    0.458  0.382   0.589  0.358  16.688
       t2n 随机森林    0.331  0.304   0.382  0.176   8.200
  diacetyl 随机森林    0.358  0.320   0.425  0.172  10.457
stale_hops 均值基准    0.304  0.304   0.389 -0.006   0.000
    orange 随机森林    0.379  0.275   0.575  0.451  27.476
 coriander 随机森林    0.248  0.195   0.324  0.164  21.127
     clove 随机森林    0.253  0.210   0.343  0.315  17.142
    lactic 随机森林    0.464  0.220   0.490  0.420  52.667
    acetic 随机森林    0.432  0.181   0.424  0.523  58.099
  barnyard 均值基准    0.323  0.323   0.404 -0.004   0.000
   overall 随机森林    0.468  0.415   0.565  0.174  11.213

测试MAE优于基准的指标数： 17 / 20

In [56]:
# 1. 合并模型选择、测试指标和预测明细
selection_50 = pd.concat([
    selection,
    extra_selection.drop(columns=["CV改善率%"])
], ignore_index=True)

test_results_50 = pd.concat([
    test_results,
    extra_test_results
], ignore_index=True)

test_predictions_50 = pd.concat([
    test_predictions,
    extra_test_predictions
], ignore_index=True)

# 2. 检查是否漏项、重复，以及测试样本是否一致
expected_targets = score_mapping["附件4字段"].tolist()

for table in [selection_50, test_results_50]:
    assert len(table) == 50
    assert table["指标"].is_unique
    assert set(table["指标"]) == set(expected_targets)

assert not test_predictions_50.duplicated(["beer", "指标"]).any()
assert set(test_predictions_50["指标"]) == set(expected_targets)

for target, group in test_predictions_50.groupby("指标"):
    assert len(group) == len(X_test)
    assert set(group["beer"]) == set(X_test.index)

# 3. 按评分卡顺序排列两个汇总表
selection_50 = (
    selection_50.set_index("指标")
    .loc[expected_targets].reset_index()
)

test_results_50 = (
    test_results_50.set_index("指标")
    .loc[expected_targets].reset_index()
)

# 4. 另存新文件，保留原来的30项结果
output_dir.mkdir(parents=True, exist_ok=True)

tables_to_save = {
    "score_dimension_mapping.csv": score_mapping,
    "model_selection_cv_50.csv": selection_50,
    "test_metrics_50.csv": test_results_50,
    "test_predictions_50.csv": test_predictions_50
}

for filename, table in tables_to_save.items():
    table.to_csv(
        output_dir / filename,
        index=False,
        encoding="utf-8-sig"
    )

# 5. 汇总：各项标准化评分MAE的等权平均
base_mae = test_results_50["测试基准MAE"].mean()
model_mae = test_results_50["测试MAE"].mean()

print("评分维度数：", len(test_results_50))
print("预测明细行数：", len(test_predictions_50))
print("优于基准的维度数：",
      (test_results_50["测试改善率%"] > 0).sum())
print(f"平均基准MAE：{base_mae:.4f}")
print(f"平均模型MAE：{model_mae:.4f}")
print(f"平均MAE的相对降幅：{(1-model_mae/base_mae)*100:.2f}%")
print("保存位置：", output_dir.resolve())

评分维度数： 50
预测明细行数： 2500
优于基准的维度数： 42
平均基准MAE：0.4120
平均模型MAE：0.3380
平均MAE的相对降幅：17.97%
保存位置： C:\Users\Lenovo\PycharmProjects\PythonProject2\outputs

In [60]:
# 7档需要6个内部界点，全部由训练集确定
all_targets = score_mapping["附件4字段"].tolist()
train_scores_50 = Y.loc[X_train.index, all_targets]

grade_cutpoints = train_scores_50.quantile(
    [i / 7 for i in range(1, 7)]
).T

grade_cutpoints.columns = [
    f"界点{i}" for i in range(1, 7)
]

grade_check = pd.DataFrame({
    "训练集不同取值数": train_scores_50.nunique(),
    "不同分界点数": grade_cutpoints.nunique(axis=1),
    "最常见值占比": train_scores_50.apply(
        lambda s: s.value_counts(normalize=True).iloc[0]
    )
})

print("检查维度数：", len(grade_check))

print("\n存在重复分界点的维度：")
problem_dims = grade_check[
    grade_check["不同分界点数"] < 6
]
print(problem_dims.round(3).to_string())

print("\n前三个整体香气指标的分界点：")
print(
    grade_cutpoints.loc[
        ["A_malt_all", "A_hops_all", "A_esters_all"]
    ].round(3).to_string()
)

检查维度数： 50

存在重复分界点的维度：
Empty DataFrame
Columns: [训练集不同取值数, 不同分界点数, 最常见值占比]
Index: []

前三个整体香气指标的分界点：
                界点1    界点2    界点3    界点4    界点5    界点6
A_malt_all   -0.648 -0.477 -0.241 -0.033  0.374  0.726
A_hops_all   -0.667 -0.425 -0.178  0.059  0.251  0.689
A_esters_all -0.581 -0.323 -0.077  0.106  0.374  0.636

In [61]:
# 保留原始连续预测，另加等级列
relative_grade_test = test_predictions_50.copy()

for target, group in relative_grade_test.groupby("指标"):
    cuts = grade_cutpoints.loc[target].to_numpy(dtype=float)

    # 小于第一个界点为0级，超过最后一个界点为6级
    relative_grade_test.loc[group.index, "真实标签相对等级"] = (
        np.searchsorted(
            cuts, group["真实值"].to_numpy(), side="right"
        )
    )

    relative_grade_test.loc[group.index, "预测相对等级"] = (
        np.searchsorted(
            cuts, group["预测值"].to_numpy(), side="right"
        )
    )

grade_cols = ["真实标签相对等级", "预测相对等级"]
relative_grade_test[grade_cols] = (
    relative_grade_test[grade_cols].astype(int)
)

relative_grade_test["等级绝对误差"] = (
    relative_grade_test["预测相对等级"]
    - relative_grade_test["真实标签相对等级"]
).abs()

# 基准：把原有训练均值预测按相同界点转换
for target, group in relative_grade_test.groupby("指标"):
    cuts = grade_cutpoints.loc[target].to_numpy(dtype=float)

    relative_grade_test.loc[group.index, "基准相对等级"] = (
        np.searchsorted(
            cuts, group["基准预测值"].to_numpy(), side="right"
        )
    )

relative_grade_test["基准相对等级"] = (
    relative_grade_test["基准相对等级"].astype(int)
)

base_grade_error = (
    relative_grade_test["基准相对等级"]
    - relative_grade_test["真实标签相对等级"]
).abs()

errors = relative_grade_test["等级绝对误差"]

print(f"模型等级MAE：{errors.mean():.3f}")
print(f"原均值基准的等级MAE：{base_grade_error.mean():.3f}")
print(f"等级完全一致率：{errors.eq(0).mean():.1%}")
print(f"相差不超过1级的比例：{errors.le(1).mean():.1%}")

模型等级MAE：1.542
原均值基准的等级MAE：1.842
等级完全一致率：20.4%
相差不超过1级的比例：56.5%

In [62]:
# 为每个维度建立训练集等级中位数基准
median_grade_baseline = {}

for target in all_targets:
    cuts = grade_cutpoints.loc[target].to_numpy(dtype=float)

    train_grades = np.searchsorted(
        cuts,
        train_scores_50[target].dropna().to_numpy(),
        side="right"
    )

    # 中位数若为半整数，取下方整数，仍是绝对误差的最优常数之一
    median_grade_baseline[target] = int(
        np.floor(np.median(train_grades))
    )

relative_grade_test["等级中位数基准"] = (
    relative_grade_test["指标"].map(median_grade_baseline)
)

median_errors = (
    relative_grade_test["等级中位数基准"]
    - relative_grade_test["真实标签相对等级"]
).abs()

model_errors = relative_grade_test["等级绝对误差"]

comparison_grades = pd.DataFrame({
    "模型": ["等级中位数基准", "当前预测模型"],
    "等级MAE": [
        median_errors.mean(),
        model_errors.mean()
    ],
    "完全一致率%": [
        median_errors.eq(0).mean() * 100,
        model_errors.eq(0).mean() * 100
    ],
    "相差不超过1级%": [
        median_errors.le(1).mean() * 100,
        model_errors.le(1).mean() * 100
    ]
})

print(comparison_grades.round(3).to_string(index=False))

     模型  等级MAE  完全一致率%  相差不超过1级%
等级中位数基准  1.724   13.84     42.28
 当前预测模型  1.542   20.44     56.48

In [63]:
calibrated = pd.read_excel(
    data_dir / "8.xlsx",
    sheet_name="Calibrated chemical dataset"
)

assert chem["beer"].is_unique
assert calibrated["beer"].is_unique

chem_by_beer = chem.set_index("beer")
cal_by_beer = calibrated.set_index("beer")

check_features = ["DMS", "X2.3.butanedione", "X4VG"]
check_rows = []

for feature in check_features:
    paired = pd.concat([
        chem_by_beer[feature].rename("附件1"),
        cal_by_beer[feature].rename("校准浓度")
    ], axis=1, join="inner").dropna()

    # 对数只对正浓度计算
    positive = paired.loc[paired["校准浓度"] > 0]
    observed = positive["附件1"]
    concentration = positive["校准浓度"]

    candidates = {
        "原值": concentration,
        "自然对数ln": np.log(concentration),
        "常用对数log10": np.log10(concentration)
    }

    for name, candidate in candidates.items():
        difference = (observed - candidate).abs()

        check_rows.append({
            "化学字段": feature,
            "候选变换": name,
            "正浓度样本数": len(positive),
            "平均绝对差": difference.mean(),
            "最大绝对差": difference.max()
        })

transform_check = pd.DataFrame(check_rows)

print(transform_check.round(6).to_string(index=False))

            化学字段      候选变换  正浓度样本数     平均绝对差      最大绝对差
             DMS        原值     249 32.842764 517.735255
             DMS    自然对数ln     249  1.821529   3.538317
             DMS 常用对数log10     249  0.000000   0.000000
X2.3.butanedione        原值     241  0.002691   0.311016
X2.3.butanedione    自然对数ln     241  4.765991 116.929204
X2.3.butanedione 常用对数log10     241  3.623171 119.645617
            X4VG        原值      82  1.109546   1.731531
            X4VG    自然对数ln      82  1.260623   2.230192
            X4VG 常用对数log10      82  0.000000   0.000000

In [64]:
feature = "X2.3.butanedione"

diacetyl_check = pd.concat([
    chem_by_beer[feature].rename("附件1"),
    cal_by_beer[feature].rename("附件8校准浓度")
], axis=1, join="inner")

diacetyl_check["绝对差"] = (
    diacetyl_check["附件1"]
    - diacetyl_check["附件8校准浓度"]
).abs()

valid = diacetyl_check.dropna(
    subset=["附件1", "附件8校准浓度"]
)

print("共同有效样本数：", len(valid))
print("差异超过0.000001的样本数：",
      (valid["绝对差"] > 1e-6).sum())

print("\n差异最大的10款：")
print(
    valid.sort_values("绝对差", ascending=False)
    .head(10)
    .to_string()
)

print("\n任一表存在缺失值的样本：")
print(
    diacetyl_check[
        diacetyl_check[["附件1", "附件8校准浓度"]]
        .isna().any(axis=1)
    ].to_string()
)

共同有效样本数： 241
差异超过0.000001的样本数： 3

差异最大的10款：
             附件1     附件8校准浓度           绝对差
beer
156     0.434130    0.123114  3.110158e-01
34      0.289622    0.530466  2.408436e-01
151     0.139752    0.043173  9.657899e-02
108     0.000050    0.000050  5.000000e-08
73    121.731018  121.731018  4.600001e-08
6       0.000027    0.000027  4.500000e-08
208     0.000011    0.000011  4.000000e-08
57      0.000089    0.000089  2.650000e-08
242     0.000016    0.000016  2.650000e-08
16      0.000089    0.000089  1.850000e-08

任一表存在缺失值的样本：
      附件1  附件8校准浓度  绝对差
beer
33    NaN      0.0  NaN
44    NaN      0.0  NaN
223   NaN      0.0  NaN
26    NaN      0.0  NaN
176   NaN      0.0  NaN
129   NaN      0.0  NaN
119   NaN      0.0  NaN
28    NaN      0.0  NaN
199   NaN      0.0  NaN

In [65]:
for feature in ["DMS", "X4VG"]:
    paired = pd.concat([
        chem_by_beer[feature].rename("附件1"),
        cal_by_beer[feature].rename("附件8浓度")
    ], axis=1, join="inner")

    zero_rows = paired.loc[paired["附件8浓度"] == 0]
    positive_rows = paired.loc[paired["附件8浓度"] > 0]

    print(f"\n===== {feature} =====")
    print("附件8零值样本数：", len(zero_rows))
    print("这些样本在附件1中的缺失数：",
          zero_rows["附件1"].isna().sum())

    print("\n零浓度对应的附件1取值及频数：")
    print(zero_rows["附件1"].value_counts(dropna=False).to_string())

    print("\n最小的5个正浓度及其附件1取值：")
    print(
        positive_rows.sort_values("附件8浓度")
        .head(5).to_string()
    )

    zero_codes = zero_rows["附件1"].dropna().unique()
    overlap = positive_rows["附件1"].isin(zero_codes).sum()
    print("\n正浓度样本中，与零值编码完全相同的数量：", overlap)

===== DMS =====
附件8零值样本数： 1
这些样本在附件1中的缺失数： 0

零浓度对应的附件1取值及频数：
附件1
0.046211    1

最小的5个正浓度及其附件1取值：
           附件1     附件8浓度
beer
86    0.347241  2.224545
40    0.553356  3.575655
54    0.633889  4.304170
179   0.653400  4.501940
161   0.754673  5.684250

正浓度样本中，与零值编码完全相同的数量： 0

===== X4VG =====
附件8零值样本数： 168
这些样本在附件1中的缺失数： 0

零浓度对应的附件1取值及频数：
附件1
-2.013157    168

最小的5个正浓度及其附件1取值：
           附件1     附件8浓度
beer
230  -1.712127  0.019403
150  -1.697453  0.020070
86   -1.664994  0.021628
203  -1.599678  0.025138
201  -1.542572  0.028670

正浓度样本中，与零值编码完全相同的数量： 0

In [66]:
threshold_info = pd.read_excel(
    data_dir / "8.xlsx",
    sheet_name="Sensory thresholds"
)

threshold_info["field_name_R"] = (
    threshold_info["field_name_R"].astype("string").str.strip()
)

# 三项已检查的物质，加上题目提到的反式-2-壬烯醛
defect_fields = [
    "DMS",
    "X2.3.butanedione",
    "X4VG",
    "X.E..2.nonenal"
]

columns_to_show = [
    "field_name_R",
    "chemical_name",
    "calibrated",
    "unit",
    "off_flavors",
    "threshold_mean",
    "threshold_median"
]

defect_thresholds = threshold_info.loc[
    threshold_info["field_name_R"].isin(defect_fields),
    columns_to_show
]

print(defect_thresholds.to_string(index=False))

print("\n未找到阈值记录的字段：")
print([
    field for field in defect_fields
    if field not in defect_thresholds["field_name_R"].tolist()
])

    field_name_R    chemical_name calibrated unit                                                                                          off_flavors  threshold_mean  threshold_median
  X.E..2.nonenal      E-2-nonenal   yes_gcms mg/L                                                                                                  NaN             NaN               NaN
X2.3.butanedione         Diacetyl   yes_gcms mg/L                                                                   butterscotch, popcorn, oily, milky        0.299250              0.09
            X4VG  4-vinylguaiacol   yes_gcms mg/L                                                                                                  NaN        0.206333              0.20
             DMS Dimethyl sulfide        yes ug/L cooked vegetables, onion, garlic, corn, black currant, sulfidic, cabbage, tinned tomato, baked beans       17.250000             19.00

未找到阈值记录的字段：
[]

In [67]:
thresholds = {
    "DMS": 19.0,               # ug/L
    "X2.3.butanedione": 0.09,  # mg/L
    "X4VG": 0.20              # mg/L
}

risk_rows = []

for feature, threshold in thresholds.items():
    concentration = cal_by_beer[feature].copy()

    # 附件1缺失、附件8为0的双乙酰样本：
    # 暂视为未知，不纳入有效样本统计
    if feature == "X2.3.butanedione":
        original = chem_by_beer[feature].reindex(concentration.index)
        unknown = original.isna() & concentration.eq(0)
        concentration = concentration.mask(unknown)

    valid = concentration.dropna()
    ratio = valid / threshold

    risk_rows.append({
        "化学字段": feature,
        "采用阈值": threshold,
        "有效样本数": len(valid),
        "未知样本数": concentration.isna().sum(),
        "超过阈值数量": ratio.gt(1).sum(),
        "超过阈值比例%": ratio.gt(1).mean() * 100,
        "浓度阈值比中位数": ratio.median(),
        "最大浓度阈值比": ratio.max()
    })

defect_baseline = pd.DataFrame(risk_rows)

print(defect_baseline.round(3).to_string(index=False))

            化学字段  采用阈值  有效样本数  未知样本数  超过阈值数量  超过阈值比例%  浓度阈值比中位数  最大浓度阈值比
             DMS 19.00    250      0     156   62.400     1.276   27.392
X2.3.butanedione  0.09    241      9     172   71.369     3.154 1352.567
            X4VG  0.20    250      0      18    7.200     0.000    3.424